In [1]:
print("Dadwal Motors - Automotive Analytics")
print("Data Generation Environment Ready")

Dadwal Motors - Automotive Analytics
Data Generation Environment Ready

In [2]:
# Dadwal Motors - Automotive Analytics
# Synthetic Data Generator

import pandas as pd
import numpy as np

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [3]:
# Project configuration

START_DATE = "2022-01-01"
END_DATE = "2025-12-31"

NUM_DEALERSHIPS = 10
NUM_VEHICLES = 25
NUM_SALESPEOPLE = 80
NUM_CUSTOMERS = 125_000
MIN_TRANSACTIONS = 500_000

print(f"Timeline: {START_DATE} to {END_DATE}")
print(f"Customers: {NUM_CUSTOMERS:,}")
print(f"Minimum transactions: {MIN_TRANSACTIONS:,}")

Timeline: 2022-01-01 to 2025-12-31
Customers: 125,000
Minimum transactions: 500,000

In [4]:
# Reproducibility

SEED = 42

np.random.seed(SEED)

print(f"Random seed set to: {SEED}")

Random seed set to: 42

In [5]:
# Create project date range

dates = pd.date_range(
    start=START_DATE,
    end=END_DATE,
    freq="D"
)

print(f"First date: {dates.min().date()}")
print(f"Last date:  {dates.max().date()}")
print(f"Total days: {len(dates):,}")

First date: 2022-01-01
Last date:  2025-12-31
Total days: 1,461

In [6]:
# Create monthly framework

months = pd.date_range(
    start=START_DATE,
    end=END_DATE,
    freq="MS"
)

monthly_framework = pd.DataFrame({
    "MonthStart": months,
    "Year": months.year,
    "MonthNumber": months.month,
    "MonthName": months.strftime("%B")
})

print(f"Total months: {len(monthly_framework)}")
display(monthly_framework.head())

Total months: 48

  MonthStart  Year  MonthNumber MonthName
0 2022-01-01  2022            1   January
1 2022-02-01  2022            2  February
2 2022-03-01  2022            3     March
3 2022-04-01  2022            4     April
4 2022-05-01  2022            5       May

In [7]:
# Vehicle master data

vehicles = [
    # Northstar
    ("V001", "Northstar", "Nova", "Passenger Car", "Sedan"),
    ("V002", "Northstar", "Metro", "Passenger Car", "Hatchback"),
    ("V003", "Northstar", "Crest", "SUV", "Compact SUV"),
    ("V004", "Northstar", "Horizon", "SUV", "Midsize SUV"),
    ("V005", "Northstar", "Titan", "Truck", "Light-Duty Pickup"),

    # Apex
    ("V006", "Apex", "A4", "Passenger Car", "Sedan"),
    ("V007", "Apex", "A6", "Passenger Car", "Coupe"),
    ("V008", "Apex", "A7", "SUV", "Midsize SUV"),
    ("V009", "Apex", "A9", "SUV", "Full-size SUV"),
    ("V010", "Apex", "X1", "Van", "Passenger Van"),

    # Summit
    ("V011", "Summit", "Ranger", "Truck", "Light-Duty Pickup"),
    ("V012", "Summit", "Frontier", "Truck", "Heavy-Duty Pickup"),
    ("V013", "Summit", "Atlas", "Truck", "Commercial Truck"),
    ("V014", "Summit", "Trail", "SUV", "Midsize SUV"),
    ("V015", "Summit", "Peak", "SUV", "Full-size SUV"),

    # Velocity
    ("V016", "Velocity", "V1", "Passenger Car", "Hatchback"),
    ("V017", "Velocity", "V3", "Passenger Car", "Coupe"),
    ("V018", "Velocity", "V5", "Passenger Car", "Sedan"),
    ("V019", "Velocity", "V7", "SUV", "Compact SUV"),
    ("V020", "Velocity", "V9", "SUV", "Midsize SUV"),

    # Evergreen
    ("V021", "Evergreen", "E1", "Passenger Car", "Hatchback"),
    ("V022", "Evergreen", "E2", "Passenger Car", "Sedan"),
    ("V023", "Evergreen", "Eco", "SUV", "Compact SUV"),
    ("V024", "Evergreen", "Transit", "Van", "Cargo Van"),
    ("V025", "Evergreen", "Carrier", "Van", "Passenger Van"),
]

vehicles = pd.DataFrame(
    vehicles,
    columns=[
        "VehicleID",
        "Brand",
        "Model",
        "VehicleType",
        "VehicleCategory"
    ]
)

print(f"Vehicles created: {len(vehicles)}")
display(vehicles)

Vehicles created: 25

   VehicleID      Brand     Model    VehicleType    VehicleCategory
0       V001  Northstar      Nova  Passenger Car              Sedan
1       V002  Northstar     Metro  Passenger Car          Hatchback
2       V003  Northstar     Crest            SUV        Compact SUV
3       V004  Northstar   Horizon            SUV        Midsize SUV
4       V005  Northstar     Titan          Truck  Light-Duty Pickup
5       V006       Apex        A4  Passenger Car              Sedan
6       V007       Apex        A6  Passenger Car              Coupe
7       V008       Apex        A7            SUV        Midsize SUV
8       V009       Apex        A9            SUV      Full-size SUV
9       V010       Apex        X1            Van      Passenger Van
10      V011     Summit    Ranger          Truck  Light-Duty Pickup
11      V012     Summit  Frontier          Truck  Heavy-Duty Pickup
12      V013     Summit     Atlas          Truck   Commercial Truck
13      V014     Summit     Trail            SUV        Midsize SUV
14      V015     Summit      Peak            SUV      Full-size SUV
15      V016   Velocity        V1  Passenger Car          Hatchback
16      V017   Velocity        V3  Passenger Car              Coupe
17      V018   Velocity        V5  Passenger Car              Sedan
18      V019   Velocity        V7            SUV        Compact SUV
19      V020   Velocity        V9            SUV        Midsize SUV
20      V021  Evergreen        E1  Passenger Car          Hatchback
21      V022  Evergreen        E2  Passenger Car              Sedan
22      V023  Evergreen       Eco            SUV        Compact SUV
23      V024  Evergreen   Transit            Van          Cargo Van
24      V025  Evergreen   Carrier            Van      Passenger Van

In [8]:
# Add vehicle attributes

msrp_ranges = {
    "Passenger Car": (25000, 65000),
    "SUV": (30000, 80000),
    "Truck": (40000, 90000),
    "Van": (35000, 75000)
}

fuel_options = ["Gasoline", "Hybrid", "Electric"]

vehicles["MSRP"] = vehicles["VehicleType"].apply(
    lambda x: np.random.randint(
        msrp_ranges[x][0] // 1000,
        msrp_ranges[x][1] // 1000 + 1
    ) * 1000
)

vehicles["FuelType"] = np.random.choice(
    fuel_options,
    size=len(vehicles),
    p=[0.60, 0.25, 0.15]
)

vehicles["ModelYear"] = np.random.choice(
    [2022, 2023, 2024, 2025],
    size=len(vehicles),
    p=[0.15, 0.25, 0.30, 0.30]
)

print("Vehicle attributes added successfully.")
display(vehicles)

Vehicle attributes added successfully.

,VehicleID,Brand,Model,VehicleType,VehicleCategory,MSRP,FuelType,ModelYear
0,V001,Northstar,Nova,Passenger Car,Sedan,63000,Gasoline,2024
1,V002,Northstar,Metro,Passenger Car,Hatchback,53000,Gasoline,2022
2,V003,Northstar,Crest,SUV,Compact SUV,44000,Gasoline,2025
3,V004,Northstar,Horizon,SUV,Midsize SUV,72000,Gasoline,2023
4,V005,Northstar,Titan,Truck,Light-Duty Pickup,47000,Hybrid,2024
5,V006,Apex,A4,Passenger Car,Sedan,45000,Gasoline,2023
6,V007,Apex,A6,Passenger Car,Coupe,63000,Gasoline,2024
7,V008,Apex,A7,SUV,Midsize SUV,48000,Gasoline,2024
8,V009,Apex,A9,SUV,Full-size SUV,52000,Gasoline,2023
9,V010,Apex,X1,Van,Passenger Van,45000,Hybrid,2025
10,V011,Summit,Ranger,Truck,Light-Duty Pickup,50000,Gasoline,2025
11,V012,Summit,Frontier,Truck,Heavy-Duty Pickup,63000,Gasoline,2025
12,V013,Summit,Atlas,Truck,Commercial Truck,75000,Gasoline,2025
13,V014,Summit,Trail,SUV,Midsize SUV,69000,Gasoline,2024
14,V015,Summit,Peak,SUV,Full-size SUV,53000,Hybrid,2025
15,V016,Velocity,V1,Passenger Car,Hatchback,27000,Gasoline,2022
16,V017,Velocity,V3,Passenger Car,Coupe,46000,Gasoline,2023
17,V018,Velocity,V5,Passenger Car,Sedan,26000,Electric,2022
18,V019,Velocity,V7,SUV,Compact SUV,53000,Electric,2023
19,V020,Velocity,V9,SUV,Midsize SUV,73000,Hybrid,2023
20,V021,Evergreen,E1,Passenger Car,Hatchback,54000,Gasoline,2023
21,V022,Evergreen,E2,Passenger Car,Sedan,62000,Gasoline,2025
22,V023,Evergreen,Eco,SUV,Compact SUV,31000,Hybrid,2023
23,V024,Evergreen,Transit,Van,Cargo Van,55000,Gasoline,2023
24,V025,Evergreen,Carrier,Van,Passenger Van,67000,Gasoline,2024

In [9]:
# Dealership master data

dealerships = [
    ("D001", "Dadwal Motors Oakville", "Oakville", "Ontario", "GTA West", "Oakville-Burlington"),
    ("D002", "Dadwal Motors Mississauga", "Mississauga", "Ontario", "GTA West", "Mississauga-Brampton"),
    ("D003", "Dadwal Motors Toronto", "Toronto", "Ontario", "GTA Central", "Toronto Central"),
    ("D004", "Dadwal Motors Vaughan", "Vaughan", "Ontario", "GTA North", "Vaughan-Richmond Hill"),
    ("D005", "Dadwal Motors Ottawa", "Ottawa", "Ontario", "Eastern Ontario", "Ottawa-Gatineau"),
    ("D006", "Dadwal Motors London", "London", "Ontario", "Southwestern Ontario", "London-Middlesex"),
    ("D007", "Dadwal Motors Kitchener", "Kitchener", "Ontario", "Waterloo Region", "Kitchener-Waterloo"),
    ("D008", "Dadwal Motors Calgary", "Calgary", "Alberta", "Southern Alberta", "Calgary Metro"),
    ("D009", "Dadwal Motors Edmonton", "Edmonton", "Alberta", "Northern Alberta", "Edmonton Metro"),
    ("D010", "Dadwal Motors Vancouver", "Vancouver", "British Columbia", "Lower Mainland", "Vancouver Metro"),
]

dealerships = pd.DataFrame(
    dealerships,
    columns=[
        "DealershipID",
        "DealershipName",
        "City",
        "Province",
        "Region",
        "AOR"
    ]
)

print(f"Dealerships created: {len(dealerships)}")
display(dealerships)

Dealerships created: 10

,DealershipID,DealershipName,City,Province,Region,AOR
0,D001,Dadwal Motors Oakville,Oakville,Ontario,GTA West,Oakville-Burlington
1,D002,Dadwal Motors Mississauga,Mississauga,Ontario,GTA West,Mississauga-Brampton
2,D003,Dadwal Motors Toronto,Toronto,Ontario,GTA Central,Toronto Central
3,D004,Dadwal Motors Vaughan,Vaughan,Ontario,GTA North,Vaughan-Richmond Hill
4,D005,Dadwal Motors Ottawa,Ottawa,Ontario,Eastern Ontario,Ottawa-Gatineau
5,D006,Dadwal Motors London,London,Ontario,Southwestern Ontario,London-Middlesex
6,D007,Dadwal Motors Kitchener,Kitchener,Ontario,Waterloo Region,Kitchener-Waterloo
7,D008,Dadwal Motors Calgary,Calgary,Alberta,Southern Alberta,Calgary Metro
8,D009,Dadwal Motors Edmonton,Edmonton,Alberta,Northern Alberta,Edmonton Metro
9,D010,Dadwal Motors Vancouver,Vancouver,British Columbia,Lower Mainland,Vancouver Metro

In [10]:
# Salesperson master data

salespeople = []

first_names = [
    "Alex", "Sarah", "Daniel", "Emily", "Ryan",
    "Olivia", "James", "Sophia", "Michael", "Emma",
    "David", "Chloe", "Matthew", "Mia", "Andrew",
    "Ava", "Thomas", "Grace", "William", "Lily"
]

last_names = [
    "Morgan", "Chen", "Brooks", "Carter", "Wilson",
    "Martin", "Taylor", "Anderson", "Brown", "Clark",
    "Lewis", "Walker", "Hall", "Young", "King",
    "Wright", "Scott", "Green", "Baker", "Adams"
]

salesperson_number = 1

for _, dealership in dealerships.iterrows():

    dealership_id = dealership["DealershipID"]

    # 6 Retail
    for _ in range(6):
        salespeople.append((
            f"SP{salesperson_number:03d}",
            f"{np.random.choice(first_names)} {np.random.choice(last_names)}",
            dealership_id,
            pd.Timestamp(
                np.random.choice(
                    pd.date_range("2018-01-01", "2024-12-31")
                )
            ),
            "Retail"
        ))
        salesperson_number += 1

    # 1 Commercial
    salespeople.append((
        f"SP{salesperson_number:03d}",
        f"{np.random.choice(first_names)} {np.random.choice(last_names)}",
        dealership_id,
        pd.Timestamp(
            np.random.choice(
                pd.date_range("2018-01-01", "2024-12-31")
            )
        ),
        "Commercial"
    ))
    salesperson_number += 1

    # 1 Fleet
    salespeople.append((
        f"SP{salesperson_number:03d}",
        f"{np.random.choice(first_names)} {np.random.choice(last_names)}",
        dealership_id,
        pd.Timestamp(
            np.random.choice(
                pd.date_range("2018-01-01", "2024-12-31")
            )
        ),
        "Fleet"
    ))
    salesperson_number += 1


salespeople = pd.DataFrame(
    salespeople,
    columns=[
        "SalespersonID",
        "SalespersonName",
        "DealershipID",
        "HireDate",
        "SalesTeam"
    ]
)

print(f"Salespeople created: {len(salespeople)}")
display(salespeople.head(10))

Salespeople created: 80

  SalespersonID SalespersonName DealershipID   HireDate   SalesTeam
0         SP001    Michael King         D001 2018-03-06      Retail
1         SP002     James Brown         D001 2021-09-29      Retail
2         SP003     Alex Walker         D001 2022-02-04      Retail
3         SP004     David Baker         D001 2019-01-27      Retail
4         SP005   Daniel Brooks         D001 2024-05-25      Retail
5         SP006      Ryan Clark         D001 2024-03-28      Retail
6         SP007  Michael Taylor         D001 2018-07-20  Commercial
7         SP008   Sophia Walker         D001 2019-05-18       Fleet
8         SP009     Ryan Brooks         D002 2023-03-11      Retail
9         SP010   Daniel Morgan         D002 2022-01-25      Retail

In [11]:
# Customer master data

NUM_CUSTOMERS = 125_000

customer_segments = ["Retail", "Premium", "Commercial", "Fleet"]

segment_probabilities = [0.65, 0.15, 0.12, 0.08]

cities_by_province = {
    "Ontario": [
        "Oakville", "Mississauga", "Toronto", "Vaughan",
        "Ottawa", "London", "Kitchener"
    ],
    "Alberta": [
        "Calgary", "Edmonton"
    ],
    "British Columbia": [
        "Vancouver"
    ]
}

province_probabilities = [0.70, 0.20, 0.10]

first_names = [
    "Alex", "Sarah", "Daniel", "Emily", "Ryan",
    "Olivia", "James", "Sophia", "Michael", "Emma",
    "David", "Chloe", "Matthew", "Mia", "Andrew",
    "Ava", "Thomas", "Grace", "William", "Lily",
    "Noah", "Amelia", "Lucas", "Ella", "Ethan",
    "Charlotte", "Benjamin", "Harper", "Henry", "Sofia"
]

last_names = [
    "Morgan", "Chen", "Brooks", "Carter", "Wilson",
    "Martin", "Taylor", "Anderson", "Brown", "Clark",
    "Lewis", "Walker", "Hall", "Young", "King",
    "Wright", "Scott", "Green", "Baker", "Adams",
    "Patel", "Singh", "Thompson", "Campbell", "Mitchell"
]

genders = ["Female", "Male", "Non-Binary"]

customers = []

for i in range(1, NUM_CUSTOMERS + 1):

    province = np.random.choice(
        ["Ontario", "Alberta", "British Columbia"],
        p=province_probabilities
    )

    city = np.random.choice(cities_by_province[province])

    segment = np.random.choice(
        customer_segments,
        p=segment_probabilities
    )

    age = np.random.randint(21, 76)

    registration_date = pd.Timestamp(
        np.random.choice(
            pd.date_range(
                "2020-01-01",
                "2025-12-31"
            )
        )
    )

    customers.append((
        f"C{i:06d}",
        np.random.choice(first_names),
        np.random.choice(last_names),
        np.random.choice(genders),
        age,
        city,
        province,
        None,
        segment,
        registration_date
    ))

customers = pd.DataFrame(
    customers,
    columns=[
        "CustomerID",
        "FirstName",
        "LastName",
        "Gender",
        "Age",
        "City",
        "Province",
        "PostalCode",
        "CustomerSegment",
        "RegistrationDate"
    ]
)

print(f"Customers created: {len(customers):,}")
display(customers.head(10))

Customers created: 125,000

,CustomerID,FirstName,LastName,Gender,Age,City,Province,PostalCode,CustomerSegment,RegistrationDate
0,C000001,Ava,Taylor,Female,53,Mississauga,Ontario,None,Premium,2020-09-02
1,C000002,Harper,Taylor,Female,45,Mississauga,Ontario,None,Commercial,2021-06-08
2,C000003,Mia,Walker,Non-Binary,66,Vaughan,Ontario,None,Retail,2021-02-03
3,C000004,Amelia,Baker,Female,52,Vaughan,Ontario,None,Retail,2025-06-05
4,C000005,Emma,Martin,Non-Binary,42,London,Ontario,None,Retail,2024-09-11
5,C000006,Chloe,Walker,Female,28,Vaughan,Ontario,None,Retail,2024-05-14
6,C000007,Daniel,Thompson,Female,72,London,Ontario,None,Retail,2020-02-16
7,C000008,Ella,Baker,Male,39,Vancouver,British Columbia,None,Premium,2021-10-18
8,C000009,Michael,Walker,Female,43,Ottawa,Ontario,None,Retail,2023-02-24
9,C000010,Sofia,Singh,Female,54,Mississauga,Ontario,None,Retail,2023-01-24

In [12]:
# Generate fictional Canadian-style postal FSAs

fsa_by_city = {
    "Oakville": ["L6H", "L6J", "L6K", "L6M"],
    "Mississauga": ["L4T", "L4V", "L4W", "L5A", "L5B"],
    "Toronto": ["M1B", "M2N", "M4B", "M5V", "M6K"],
    "Vaughan": ["L4H", "L4J", "L4K", "L6A"],
    "Ottawa": ["K1A", "K1B", "K1G", "K1K", "K2P"],
    "London": ["N5V", "N5W", "N5Y", "N6A", "N6B"],
    "Kitchener": ["N2A", "N2B", "N2C", "N2E", "N2G"],
    "Calgary": ["T1Y", "T2A", "T2N", "T2P", "T3A"],
    "Edmonton": ["T5A", "T5B", "T5E", "T5H", "T6A"],
    "Vancouver": ["V5K", "V5L", "V5N", "V6B", "V6E"]
}

customers["PostalCode"] = customers["City"].apply(
    lambda city: np.random.choice(fsa_by_city[city])
)

print("Postal FSAs generated successfully.")
display(customers[[
    "CustomerID",
    "City",
    "Province",
    "PostalCode",
    "CustomerSegment"
]].head(10))

Postal FSAs generated successfully.

  CustomerID         City          Province PostalCode CustomerSegment
0    C000001  Mississauga           Ontario        L5B         Premium
1    C000002  Mississauga           Ontario        L4T      Commercial
2    C000003      Vaughan           Ontario        L4J          Retail
3    C000004      Vaughan           Ontario        L4K          Retail
4    C000005       London           Ontario        N5V          Retail
5    C000006      Vaughan           Ontario        L4K          Retail
6    C000007       London           Ontario        N5Y          Retail
7    C000008    Vancouver  British Columbia        V6E         Premium
8    C000009       Ottawa           Ontario        K1B          Retail
9    C000010  Mississauga           Ontario        L4V          Retail

In [13]:
# Validate customer master

print("Customer count:", len(customers))
print("\nCustomer segments:")
print(customers["CustomerSegment"].value_counts())

print("\nProvince distribution:")
print(customers["Province"].value_counts())

print("\nMissing values:")
print(customers.isna().sum())

Customer count: 125000

Customer segments:
CustomerSegment
Retail        81254
Premium       18927
Commercial    14784
Fleet         10035
Name: count, dtype: int64

Province distribution:
Province
Ontario             87369
Alberta             25157
British Columbia    12474
Name: count, dtype: int64

Missing values:
CustomerID          0
FirstName           0
LastName            0
Gender              0
Age                 0
City                0
Province            0
PostalCode          0
CustomerSegment     0
RegistrationDate    0
dtype: int64

In [14]:
# Create monthly dealership target framework

sales_targets = pd.MultiIndex.from_product(
    [
        dealerships["DealershipID"],
        monthly_framework["MonthStart"]
    ],
    names=["DealershipID", "TargetMonth"]
).to_frame(index=False)

sales_targets["TargetID"] = [
    f"T{i:04d}" for i in range(1, len(sales_targets) + 1)
]

# Put TargetID first
sales_targets = sales_targets[
    ["TargetID", "TargetMonth", "DealershipID"]
]

print(f"Target records created: {len(sales_targets)}")
display(sales_targets.head(10))

Target records created: 480

  TargetID TargetMonth DealershipID
0    T0001  2022-01-01         D001
1    T0002  2022-02-01         D001
2    T0003  2022-03-01         D001
3    T0004  2022-04-01         D001
4    T0005  2022-05-01         D001
5    T0006  2022-06-01         D001
6    T0007  2022-07-01         D001
7    T0008  2022-08-01         D001
8    T0009  2022-09-01         D001
9    T0010  2022-10-01         D001

In [15]:
# Add monthly seasonality factors

seasonality = {
    1: 0.85,   # January
    2: 0.90,   # February
    3: 0.95,   # March
    4: 1.00,   # April
    5: 1.05,   # May
    6: 1.10,   # June
    7: 1.08,   # July
    8: 1.05,   # August
    9: 0.98,   # September
    10: 1.02,  # October
    11: 1.12,  # November
    12: 1.18   # December
}

monthly_framework["SeasonalityFactor"] = (
    monthly_framework["MonthNumber"].map(seasonality)
)

display(
    monthly_framework[
        ["MonthStart", "MonthName", "SeasonalityFactor"]
    ]
)

   MonthStart  MonthName  SeasonalityFactor
0  2022-01-01    January               0.85
1  2022-02-01   February               0.90
2  2022-03-01      March               0.95
3  2022-04-01      April               1.00
4  2022-05-01        May               1.05
5  2022-06-01       June               1.10
6  2022-07-01       July               1.08
7  2022-08-01     August               1.05
8  2022-09-01  September               0.98
9  2022-10-01    October               1.02
10 2022-11-01   November               1.12
11 2022-12-01   December               1.18
12 2023-01-01    January               0.85
13 2023-02-01   February               0.90
14 2023-03-01      March               0.95
15 2023-04-01      April               1.00
16 2023-05-01        May               1.05
17 2023-06-01       June               1.10
18 2023-07-01       July               1.08
19 2023-08-01     August               1.05
20 2023-09-01  September               0.98
21 2023-10-01    October               1.02
22 2023-11-01   November               1.12
23 2023-12-01   December               1.18
24 2024-01-01    January               0.85
25 2024-02-01   February               0.90
26 2024-03-01      March               0.95
27 2024-04-01      April               1.00
28 2024-05-01        May               1.05
29 2024-06-01       June               1.10
30 2024-07-01       July               1.08
31 2024-08-01     August               1.05
32 2024-09-01  September               0.98
33 2024-10-01    October               1.02
34 2024-11-01   November               1.12
35 2024-12-01   December               1.18
36 2025-01-01    January               0.85
37 2025-02-01   February               0.90
38 2025-03-01      March               0.95
39 2025-04-01      April               1.00
40 2025-05-01        May               1.05
41 2025-06-01       June               1.10
42 2025-07-01       July               1.08
43 2025-08-01     August               1.05
44 2025-09-01  September               0.98
45 2025-10-01    October               1.02
46 2025-11-01   November               1.12
47 2025-12-01   December               1.18

In [16]:
# Add annual growth factors

annual_growth = {
    2022: 1.00,
    2023: 1.06,
    2024: 1.11,
    2025: 1.17
}

monthly_framework["GrowthFactor"] = (
    monthly_framework["Year"].map(annual_growth)
)

display(
    monthly_framework[
        ["MonthStart", "Year", "SeasonalityFactor", "GrowthFactor"]
    ]
)

   MonthStart  Year  SeasonalityFactor  GrowthFactor
0  2022-01-01  2022               0.85          1.00
1  2022-02-01  2022               0.90          1.00
2  2022-03-01  2022               0.95          1.00
3  2022-04-01  2022               1.00          1.00
4  2022-05-01  2022               1.05          1.00
5  2022-06-01  2022               1.10          1.00
6  2022-07-01  2022               1.08          1.00
7  2022-08-01  2022               1.05          1.00
8  2022-09-01  2022               0.98          1.00
9  2022-10-01  2022               1.02          1.00
10 2022-11-01  2022               1.12          1.00
11 2022-12-01  2022               1.18          1.00
12 2023-01-01  2023               0.85          1.06
13 2023-02-01  2023               0.90          1.06
14 2023-03-01  2023               0.95          1.06
15 2023-04-01  2023               1.00          1.06
16 2023-05-01  2023               1.05          1.06
17 2023-06-01  2023               1.10          1.06
18 2023-07-01  2023               1.08          1.06
19 2023-08-01  2023               1.05          1.06
20 2023-09-01  2023               0.98          1.06
21 2023-10-01  2023               1.02          1.06
22 2023-11-01  2023               1.12          1.06
23 2023-12-01  2023               1.18          1.06
24 2024-01-01  2024               0.85          1.11
25 2024-02-01  2024               0.90          1.11
26 2024-03-01  2024               0.95          1.11
27 2024-04-01  2024               1.00          1.11
28 2024-05-01  2024               1.05          1.11
29 2024-06-01  2024               1.10          1.11
30 2024-07-01  2024               1.08          1.11
31 2024-08-01  2024               1.05          1.11
32 2024-09-01  2024               0.98          1.11
33 2024-10-01  2024               1.02          1.11
34 2024-11-01  2024               1.12          1.11
35 2024-12-01  2024               1.18          1.11
36 2025-01-01  2025               0.85          1.17
37 2025-02-01  2025               0.90          1.17
38 2025-03-01  2025               0.95          1.17
39 2025-04-01  2025               1.00          1.17
40 2025-05-01  2025               1.05          1.17
41 2025-06-01  2025               1.10          1.17
42 2025-07-01  2025               1.08          1.17
43 2025-08-01  2025               1.05          1.17
44 2025-09-01  2025               0.98          1.17
45 2025-10-01  2025               1.02          1.17
46 2025-11-01  2025               1.12          1.17
47 2025-12-01  2025               1.18          1.17

In [17]:
# Dealership sales capacity weights

dealership_capacity = {
    "D001": 1.15,  # Oakville
    "D002": 1.20,  # Mississauga
    "D003": 1.35,  # Toronto
    "D004": 1.10,  # Vaughan
    "D005": 1.05,  # Ottawa
    "D006": 0.90,  # London
    "D007": 0.95,  # Kitchener
    "D008": 1.10,  # Calgary
    "D009": 1.00,  # Edmonton
    "D010": 1.20   # Vancouver
}

dealerships["SalesCapacityWeight"] = (
    dealerships["DealershipID"].map(dealership_capacity)
)

display(
    dealerships[
        ["DealershipID", "DealershipName", "Province", "Region",
         "SalesCapacityWeight"]
    ]
)

,DealershipID,DealershipName,Province,Region,SalesCapacityWeight
0,D001,Dadwal Motors Oakville,Ontario,GTA West,1.15
1,D002,Dadwal Motors Mississauga,Ontario,GTA West,1.20
2,D003,Dadwal Motors Toronto,Ontario,GTA Central,1.35
3,D004,Dadwal Motors Vaughan,Ontario,GTA North,1.10
4,D005,Dadwal Motors Ottawa,Ontario,Eastern Ontario,1.05
5,D006,Dadwal Motors London,Ontario,Southwestern Ontario,0.90
6,D007,Dadwal Motors Kitchener,Ontario,Waterloo Region,0.95
7,D008,Dadwal Motors Calgary,Alberta,Southern Alberta,1.10
8,D009,Dadwal Motors Edmonton,Alberta,Northern Alberta,1.00
9,D010,Dadwal Motors Vancouver,British Columbia,Lower Mainland,1.20

In [18]:
# Company-wide vehicle type demand weights

vehicle_type_weights = {
    "Passenger Car": 0.40,
    "SUV": 0.40,
    "Truck": 0.13,
    "Van": 0.07
}

print("Vehicle type demand weights:")
for vehicle_type, weight in vehicle_type_weights.items():
    print(f"{vehicle_type}: {weight:.0%}")

print(f"\nTotal: {sum(vehicle_type_weights.values()):.0%}")

Vehicle type demand weights:
Passenger Car: 40%
SUV: 40%
Truck: 13%
Van: 7%

Total: 100%

In [19]:
# Regional vehicle-type demand adjustments

regional_vehicle_weights = {
    "Ontario": {
        "Passenger Car": 0.42,
        "SUV": 0.40,
        "Truck": 0.11,
        "Van": 0.07
    },

    "Alberta": {
        "Passenger Car": 0.32,
        "SUV": 0.43,
        "Truck": 0.18,
        "Van": 0.07
    },

    "British Columbia": {
        "Passenger Car": 0.44,
        "SUV": 0.41,
        "Truck": 0.08,
        "Van": 0.07
    }
}

for province, weights in regional_vehicle_weights.items():
    print(f"\n{province}")

    for vehicle_type, weight in weights.items():
        print(f"{vehicle_type}: {weight:.0%}")

    print(f"Total: {sum(weights.values()):.0%}")

Ontario
Passenger Car: 42%
SUV: 40%
Truck: 11%
Van: 7%
Total: 100%

Alberta
Passenger Car: 32%
SUV: 43%
Truck: 18%
Van: 7%
Total: 100%

British Columbia
Passenger Car: 44%
SUV: 41%
Truck: 8%
Van: 7%
Total: 100%

In [20]:
# Customer segment vehicle preferences

segment_vehicle_weights = {
    "Retail": {
        "Passenger Car": 0.43,
        "SUV": 0.45,
        "Truck": 0.08,
        "Van": 0.04
    },

    "Premium": {
        "Passenger Car": 0.35,
        "SUV": 0.55,
        "Truck": 0.07,
        "Van": 0.03
    },

    "Commercial": {
        "Passenger Car": 0.15,
        "SUV": 0.25,
        "Truck": 0.35,
        "Van": 0.25
    },

    "Fleet": {
        "Passenger Car": 0.20,
        "SUV": 0.35,
        "Truck": 0.25,
        "Van": 0.20
    }
}

for segment, weights in segment_vehicle_weights.items():
    print(f"\n{segment}")

    for vehicle_type, weight in weights.items():
        print(f"{vehicle_type}: {weight:.0%}")

    print(f"Total: {sum(weights.values()):.0%}")

Retail
Passenger Car: 43%
SUV: 45%
Truck: 8%
Van: 4%
Total: 100%

Premium
Passenger Car: 35%
SUV: 55%
Truck: 7%
Van: 3%
Total: 100%

Commercial
Passenger Car: 15%
SUV: 25%
Truck: 35%
Van: 25%
Total: 100%

Fleet
Passenger Car: 20%
SUV: 35%
Truck: 25%
Van: 20%
Total: 100%

In [21]:
# Sales team vehicle preferences

sales_team_vehicle_weights = {
    "Retail": {
        "Passenger Car": 0.43,
        "SUV": 0.45,
        "Truck": 0.08,
        "Van": 0.04
    },

    "Commercial": {
        "Passenger Car": 0.10,
        "SUV": 0.25,
        "Truck": 0.40,
        "Van": 0.25
    },

    "Fleet": {
        "Passenger Car": 0.15,
        "SUV": 0.35,
        "Truck": 0.30,
        "Van": 0.20
    }
}

for team, weights in sales_team_vehicle_weights.items():
    print(f"\n{team}")

    for vehicle_type, weight in weights.items():
        print(f"{vehicle_type}: {weight:.0%}")

    print(f"Total: {sum(weights.values()):.0%}")

Retail
Passenger Car: 43%
SUV: 45%
Truck: 8%
Van: 4%
Total: 100%

Commercial
Passenger Car: 10%
SUV: 25%
Truck: 40%
Van: 25%
Total: 100%

Fleet
Passenger Car: 15%
SUV: 35%
Truck: 30%
Van: 20%
Total: 100%

In [22]:
# Salesperson performance weights

performance_tiers = {
    "Top Performer": {
        "probability": 0.15,
        "min_weight": 1.20,
        "max_weight": 1.45
    },
    "Strong Performer": {
        "probability": 0.30,
        "min_weight": 1.05,
        "max_weight": 1.20
    },
    "Average Performer": {
        "probability": 0.40,
        "min_weight": 0.90,
        "max_weight": 1.05
    },
    "Developing": {
        "probability": 0.15,
        "min_weight": 0.70,
        "max_weight": 0.90
    }
}

salespeople["PerformanceTier"] = np.random.choice(
    list(performance_tiers.keys()),
    size=len(salespeople),
    p=[
        performance_tiers[tier]["probability"]
        for tier in performance_tiers
    ]
)

salespeople["PerformanceWeight"] = salespeople["PerformanceTier"].apply(
    lambda tier: np.random.uniform(
        performance_tiers[tier]["min_weight"],
        performance_tiers[tier]["max_weight"]
    )
)

print("Salesperson performance profiles created.")

display(
    salespeople[
        [
            "SalespersonID",
            "SalespersonName",
            "DealershipID",
            "SalesTeam",
            "PerformanceTier",
            "PerformanceWeight"
        ]
    ].head(10)
)

Salesperson performance profiles created.

,SalespersonID,SalespersonName,DealershipID,SalesTeam,PerformanceTier,PerformanceWeight
0,SP001,Michael King,D001,Retail,Average Performer,0.980636
1,SP002,James Brown,D001,Retail,Top Performer,1.271037
2,SP003,Alex Walker,D001,Retail,Developing,0.787279
3,SP004,David Baker,D001,Retail,Average Performer,1.006429
4,SP005,Daniel Brooks,D001,Retail,Average Performer,0.980149
5,SP006,Ryan Clark,D001,Retail,Average Performer,0.930941
6,SP007,Michael Taylor,D001,Commercial,Strong Performer,1.189347
7,SP008,Sophia Walker,D001,Fleet,Top Performer,1.371836
8,SP009,Ryan Brooks,D002,Retail,Strong Performer,1.163347
9,SP010,Daniel Morgan,D002,Retail,Strong Performer,1.064192

In [23]:
# Model-level demand weights

model_demand_weights = {
    "V001": 1.25,  # Northstar Nova
    "V002": 1.05,  # Northstar Metro
    "V003": 1.10,  # Northstar Crest
    "V004": 1.20,  # Northstar Horizon
    "V005": 0.90,  # Northstar Titan

    "V006": 1.00,  # Apex A4
    "V007": 0.75,  # Apex A6
    "V008": 1.10,  # Apex A7
    "V009": 0.85,  # Apex A9
    "V010": 0.70,  # Apex X1

    "V011": 1.10,  # Summit Ranger
    "V012": 0.85,  # Summit Frontier
    "V013": 0.65,  # Summit Atlas
    "V014": 1.05,  # Summit Trail
    "V015": 0.90,  # Summit Peak

    "V016": 1.05,  # Velocity V1
    "V017": 0.80,  # Velocity V3
    "V018": 1.00,  # Velocity V5
    "V019": 1.15,  # Velocity V7
    "V020": 0.95,  # Velocity V9

    "V021": 1.15,  # Evergreen E1
    "V022": 1.30,  # Evergreen E2
    "V023": 1.10,  # Evergreen Eco
    "V024": 0.80,  # Evergreen Transit
    "V025": 0.75   # Evergreen Carrier
}

vehicles["DemandWeight"] = vehicles["VehicleID"].map(
    model_demand_weights
)

print("Model demand weights added.")

display(
    vehicles[
        [
            "VehicleID",
            "Brand",
            "Model",
            "VehicleType",
            "DemandWeight"
        ]
    ]
)

Model demand weights added.

   VehicleID      Brand     Model    VehicleType  DemandWeight
0       V001  Northstar      Nova  Passenger Car          1.25
1       V002  Northstar     Metro  Passenger Car          1.05
2       V003  Northstar     Crest            SUV          1.10
3       V004  Northstar   Horizon            SUV          1.20
4       V005  Northstar     Titan          Truck          0.90
5       V006       Apex        A4  Passenger Car          1.00
6       V007       Apex        A6  Passenger Car          0.75
7       V008       Apex        A7            SUV          1.10
8       V009       Apex        A9            SUV          0.85
9       V010       Apex        X1            Van          0.70
10      V011     Summit    Ranger          Truck          1.10
11      V012     Summit  Frontier          Truck          0.85
12      V013     Summit     Atlas          Truck          0.65
13      V014     Summit     Trail            SUV          1.05
14      V015     Summit      Peak            SUV          0.90
15      V016   Velocity        V1  Passenger Car          1.05
16      V017   Velocity        V3  Passenger Car          0.80
17      V018   Velocity        V5  Passenger Car          1.00
18      V019   Velocity        V7            SUV          1.15
19      V020   Velocity        V9            SUV          0.95
20      V021  Evergreen        E1  Passenger Car          1.15
21      V022  Evergreen        E2  Passenger Car          1.30
22      V023  Evergreen       Eco            SUV          1.10
23      V024  Evergreen   Transit            Van          0.80
24      V025  Evergreen   Carrier            Van          0.75

In [24]:
# Add dealer cost margin assumptions

cost_margin_by_type = {
    "Passenger Car": 0.82,
    "SUV": 0.80,
    "Truck": 0.78,
    "Van": 0.80
}

vehicles["CostRatio"] = vehicles["VehicleType"].map(
    cost_margin_by_type
)

# Add small model-level variation to cost
vehicles["CostRatio"] = (
    vehicles["CostRatio"]
    * np.random.uniform(0.97, 1.03, len(vehicles))
)

# Keep ratios within a sensible range
vehicles["CostRatio"] = vehicles["CostRatio"].clip(
    lower=0.74,
    upper=0.86
)

vehicles["BaseCost"] = (
    vehicles["MSRP"] * vehicles["CostRatio"]
).round(-2)

print("Pricing and cost assumptions added.")

display(
    vehicles[
        [
            "VehicleID",
            "Brand",
            "Model",
            "VehicleType",
            "MSRP",
            "CostRatio",
            "BaseCost"
        ]
    ]
)

Pricing and cost assumptions added.

   VehicleID      Brand     Model    VehicleType   MSRP  CostRatio  BaseCost
0       V001  Northstar      Nova  Passenger Car  63000   0.844092   53200.0
1       V002  Northstar     Metro  Passenger Car  53000   0.844571   44800.0
2       V003  Northstar     Crest            SUV  44000   0.776701   34200.0
3       V004  Northstar   Horizon            SUV  72000   0.803750   57900.0
4       V005  Northstar     Titan          Truck  47000   0.800254   37600.0
5       V006       Apex        A4  Passenger Car  45000   0.835180   37600.0
6       V007       Apex        A6  Passenger Car  63000   0.806295   50800.0
7       V008       Apex        A7            SUV  48000   0.813432   39000.0
8       V009       Apex        A9            SUV  52000   0.786241   40900.0
9       V010       Apex        X1            Van  45000   0.808684   36400.0
10      V011     Summit    Ranger          Truck  50000   0.770127   38500.0
11      V012     Summit  Frontier          Truck  63000   0.769987   48500.0
12      V013     Summit     Atlas          Truck  75000   0.797387   59800.0
13      V014     Summit     Trail            SUV  69000   0.823786   56800.0
14      V015     Summit      Peak            SUV  53000   0.805423   42700.0
15      V016   Velocity        V1  Passenger Car  27000   0.802807   21700.0
16      V017   Velocity        V3  Passenger Car  46000   0.802336   36900.0
17      V018   Velocity        V5  Passenger Car  26000   0.797340   20700.0
18      V019   Velocity        V7            SUV  53000   0.784476   41600.0
19      V020   Velocity        V9            SUV  73000   0.808527   59000.0
20      V021  Evergreen        E1  Passenger Car  54000   0.813697   43900.0
21      V022  Evergreen        E2  Passenger Car  62000   0.813700   50400.0
22      V023  Evergreen       Eco            SUV  31000   0.781379   24200.0
23      V024  Evergreen   Transit            Van  55000   0.776028   42700.0
24      V025  Evergreen   Carrier            Van  67000   0.808606   54200.0

In [25]:
# Discount assumptions by customer segment

discount_rules = {
    "Retail": {
        "min_discount": 0.01,
        "max_discount": 0.05
    },

    "Premium": {
        "min_discount": 0.00,
        "max_discount": 0.03
    },

    "Commercial": {
        "min_discount": 0.03,
        "max_discount": 0.08
    },

    "Fleet": {
        "min_discount": 0.05,
        "max_discount": 0.12
    }
}

for segment, rules in discount_rules.items():
    print(
        f"{segment}: "
        f"{rules['min_discount']:.0%} - "
        f"{rules['max_discount']:.0%}"
    )

Retail: 1% - 5%
Premium: 0% - 3%
Commercial: 3% - 8%
Fleet: 5% - 12%

In [26]:
# Seasonal promotional discount adjustments

promotion_adjustments = {
    1: 0.00,   # January
    2: 0.00,   # February
    3: 0.00,   # March
    4: 0.00,   # April
    5: 0.005,  # May
    6: 0.005,  # June
    7: 0.005,  # July
    8: 0.005,  # August
    9: 0.00,   # September
    10: 0.005, # October
    11: 0.010, # November
    12: 0.015  # December
}

monthly_framework["PromotionAdjustment"] = (
    monthly_framework["MonthNumber"].map(promotion_adjustments)
)

display(
    monthly_framework[
        ["MonthStart", "MonthName", "PromotionAdjustment"]
    ]
)

   MonthStart  MonthName  PromotionAdjustment
0  2022-01-01    January                0.000
1  2022-02-01   February                0.000
2  2022-03-01      March                0.000
3  2022-04-01      April                0.000
4  2022-05-01        May                0.005
5  2022-06-01       June                0.005
6  2022-07-01       July                0.005
7  2022-08-01     August                0.005
8  2022-09-01  September                0.000
9  2022-10-01    October                0.005
10 2022-11-01   November                0.010
11 2022-12-01   December                0.015
12 2023-01-01    January                0.000
13 2023-02-01   February                0.000
14 2023-03-01      March                0.000
15 2023-04-01      April                0.000
16 2023-05-01        May                0.005
17 2023-06-01       June                0.005
18 2023-07-01       July                0.005
19 2023-08-01     August                0.005
20 2023-09-01  September                0.000
21 2023-10-01    October                0.005
22 2023-11-01   November                0.010
23 2023-12-01   December                0.015
24 2024-01-01    January                0.000
25 2024-02-01   February                0.000
26 2024-03-01      March                0.000
27 2024-04-01      April                0.000
28 2024-05-01        May                0.005
29 2024-06-01       June                0.005
30 2024-07-01       July                0.005
31 2024-08-01     August                0.005
32 2024-09-01  September                0.000
33 2024-10-01    October                0.005
34 2024-11-01   November                0.010
35 2024-12-01   December                0.015
36 2025-01-01    January                0.000
37 2025-02-01   February                0.000
38 2025-03-01      March                0.000
39 2025-04-01      April                0.000
40 2025-05-01        May                0.005
41 2025-06-01       June                0.005
42 2025-07-01       July                0.005
43 2025-08-01     August                0.005
44 2025-09-01  September                0.000
45 2025-10-01    October                0.005
46 2025-11-01   November                0.010
47 2025-12-01   December                0.015

In [27]:
# Validate discount assumptions

print("Discount ranges by customer segment:\n")

for segment, rules in discount_rules.items():
    print(
        f"{segment:<12} "
        f"{rules['min_discount']:.1%} - "
        f"{rules['max_discount']:.1%}"
    )

print("\nDecember promotion adjustment:")
print(f"{promotion_adjustments[12]:.1%}")

Discount ranges by customer segment:

Retail       1.0% - 5.0%
Premium      0.0% - 3.0%
Commercial   3.0% - 8.0%
Fleet        5.0% - 12.0%

December promotion adjustment:
1.5%

In [28]:
# Transaction-level cost variation

COST_VARIATION_MIN = 0.98
COST_VARIATION_MAX = 1.02

print(
    f"Transaction cost variation: "
    f"{(COST_VARIATION_MIN - 1):.1%} to "
    f"{(COST_VARIATION_MAX - 1):.1%}"
)

Transaction cost variation: -2.0% to 2.0%

In [29]:
# Baseline transaction demand

BASE_MONTHLY_SALES = 10_000

print(f"Baseline monthly sales: {BASE_MONTHLY_SALES:,}")
print(f"Minimum four-year transactions: {MIN_TRANSACTIONS:,}")

Baseline monthly sales: 10,000
Minimum four-year transactions: 500,000

In [30]:
# Natural monthly demand variation

MONTHLY_VARIATION_MIN = 0.95
MONTHLY_VARIATION_MAX = 1.05

print(
    f"Monthly natural variation: "
    f"{(MONTHLY_VARIATION_MIN - 1):.1%} to "
    f"{(MONTHLY_VARIATION_MAX - 1):.1%}"
)

Monthly natural variation: -5.0% to 5.0%

In [31]:
# Calculate expected monthly transaction volume

monthly_framework["MonthlyVariation"] = np.random.uniform(
    MONTHLY_VARIATION_MIN,
    MONTHLY_VARIATION_MAX,
    len(monthly_framework)
)

monthly_framework["ExpectedTransactions"] = (
    BASE_MONTHLY_SALES
    * monthly_framework["SeasonalityFactor"]
    * monthly_framework["GrowthFactor"]
    * monthly_framework["MonthlyVariation"]
).round().astype(int)

print(
    f"Expected four-year transactions: "
    f"{monthly_framework['ExpectedTransactions'].sum():,}"
)

display(
    monthly_framework[
        [
            "MonthStart",
            "SeasonalityFactor",
            "GrowthFactor",
            "MonthlyVariation",
            "ExpectedTransactions"
        ]
    ].head(12)
)

Expected four-year transactions: 531,477

,MonthStart,SeasonalityFactor,GrowthFactor,MonthlyVariation,ExpectedTransactions
0,2022-01-01,0.85,1.0,1.049370,8920
1,2022-02-01,0.90,1.0,0.974751,8773
2,2022-03-01,0.95,1.0,0.962735,9146
3,2022-04-01,1.00,1.0,0.987075,9871
4,2022-05-01,1.05,1.0,0.990638,10402
5,2022-06-01,1.10,1.0,0.966637,10633
6,2022-07-01,1.08,1.0,0.992593,10720
7,2022-08-01,1.05,1.0,1.041613,10937
8,2022-09-01,0.98,1.0,1.037077,10163
9,2022-10-01,1.02,1.0,0.991532,10114
10,2022-11-01,1.12,1.0,0.984539,11027
11,2022-12-01,1.18,1.0,1.040551,12279

In [32]:
# Allocate monthly transactions across dealerships

dealership_allocation = sales_targets.merge(
    monthly_framework[
        [
            "MonthStart",
            "ExpectedTransactions"
        ]
    ],
    left_on="TargetMonth",
    right_on="MonthStart",
    how="left"
)

dealership_allocation["CapacityWeight"] = (
    dealership_allocation["DealershipID"]
    .map(dealership_capacity)
)

dealership_allocation["WeightedDemand"] = (
    dealership_allocation["ExpectedTransactions"]
    * dealership_allocation["CapacityWeight"]
)

# Calculate each dealership's share within each month
dealership_allocation["MonthlyShare"] = (
    dealership_allocation["WeightedDemand"]
    /
    dealership_allocation.groupby("TargetMonth")["WeightedDemand"]
    .transform("sum")
)

dealership_allocation["AllocatedTransactions"] = (
    dealership_allocation["ExpectedTransactions"]
    * dealership_allocation["MonthlyShare"]
).round().astype(int)

print(
    f"Allocated transaction records: "
    f"{len(dealership_allocation):,}"
)

display(
    dealership_allocation[
        [
            "TargetMonth",
            "DealershipID",
            "CapacityWeight",
            "MonthlyShare",
            "AllocatedTransactions"
        ]
    ].head(10)
)

Allocated transaction records: 480

,TargetMonth,DealershipID,CapacityWeight,MonthlyShare,AllocatedTransactions
0,2022-01-01,D001,1.15,0.104545,933
1,2022-02-01,D001,1.15,0.104545,917
2,2022-03-01,D001,1.15,0.104545,956
3,2022-04-01,D001,1.15,0.104545,1032
4,2022-05-01,D001,1.15,0.104545,1087
5,2022-06-01,D001,1.15,0.104545,1112
6,2022-07-01,D001,1.15,0.104545,1121
7,2022-08-01,D001,1.15,0.104545,1143
8,2022-09-01,D001,1.15,0.104545,1062
9,2022-10-01,D001,1.15,0.104545,1057

In [33]:
# Validate dealership transaction allocation

allocation_check = (
    dealership_allocation
    .groupby("TargetMonth")["AllocatedTransactions"]
    .sum()
    .reset_index(name="AllocatedTotal")
)

allocation_check = allocation_check.merge(
    monthly_framework[
        ["MonthStart", "ExpectedTransactions"]
    ],
    left_on="TargetMonth",
    right_on="MonthStart",
    how="left"
)

allocation_check["Difference"] = (
    allocation_check["AllocatedTotal"]
    - allocation_check["ExpectedTransactions"]
)

print("Maximum allocation difference:")
print(allocation_check["Difference"].abs().max())

print("\nTotal allocated transactions:")
print(f"{allocation_check['AllocatedTotal'].sum():,}")

print("\nTotal expected transactions:")
print(f"{allocation_check['ExpectedTransactions'].sum():,}")

display(allocation_check.head(12))

Maximum allocation difference:
3

Total allocated transactions:
531,482

Total expected transactions:
531,477

   TargetMonth  AllocatedTotal MonthStart  ExpectedTransactions  Difference
0   2022-01-01            8920 2022-01-01                  8920           0
1   2022-02-01            8773 2022-02-01                  8773           0
2   2022-03-01            9146 2022-03-01                  9146           0
3   2022-04-01            9870 2022-04-01                  9871          -1
4   2022-05-01           10402 2022-05-01                 10402           0
5   2022-06-01           10633 2022-06-01                 10633           0
6   2022-07-01           10720 2022-07-01                 10720           0
7   2022-08-01           10937 2022-08-01                 10937           0
8   2022-09-01           10163 2022-09-01                 10163           0
9   2022-10-01           10111 2022-10-01                 10114          -3
10  2022-11-01           11027 2022-11-01                 11027           0
11  2022-12-01           12280 2022-12-01                 12279           1

In [34]:
# Prepare transaction row counts

transaction_counts = dealership_allocation[
    [
        "TargetMonth",
        "DealershipID",
        "AllocatedTransactions"
    ]
].copy()

print(f"Dealership-month records: {len(transaction_counts)}")
print(
    f"Transactions to generate: "
    f"{transaction_counts['AllocatedTransactions'].sum():,}"
)

display(transaction_counts.head(10))

Dealership-month records: 480
Transactions to generate: 531,482

  TargetMonth DealershipID  AllocatedTransactions
0  2022-01-01         D001                    933
1  2022-02-01         D001                    917
2  2022-03-01         D001                    956
3  2022-04-01         D001                   1032
4  2022-05-01         D001                   1087
5  2022-06-01         D001                   1112
6  2022-07-01         D001                   1121
7  2022-08-01         D001                   1143
8  2022-09-01         D001                   1062
9  2022-10-01         D001                   1057

In [35]:
# Create transaction ID sequence

TOTAL_TRANSACTIONS = int(
    transaction_counts["AllocatedTransactions"].sum()
)

transaction_ids = np.arange(
    1,
    TOTAL_TRANSACTIONS + 1
)

print(f"Transaction IDs prepared: {len(transaction_ids):,}")
print(f"First ID: S{transaction_ids[0]:06d}")
print(f"Last ID:  S{transaction_ids[-1]:06d}")

Transaction IDs prepared: 531,482
First ID: S000001
Last ID:  S531482

In [36]:
# Expand dealership-month allocations into transaction-level rows

transaction_base = transaction_counts.loc[
    transaction_counts.index.repeat(
        transaction_counts["AllocatedTransactions"]
    )
].reset_index(drop=True)

transaction_base["SalesID"] = [
    f"S{i:06d}" for i in range(1, len(transaction_base) + 1)
]

transaction_base = transaction_base[
    [
        "SalesID",
        "TargetMonth",
        "DealershipID"
    ]
]

print(f"Transaction rows created: {len(transaction_base):,}")

display(transaction_base.head(10))

Transaction rows created: 531,482

   SalesID TargetMonth DealershipID
0  S000001  2022-01-01         D001
1  S000002  2022-01-01         D001
2  S000003  2022-01-01         D001
3  S000004  2022-01-01         D001
4  S000005  2022-01-01         D001
5  S000006  2022-01-01         D001
6  S000007  2022-01-01         D001
7  S000008  2022-01-01         D001
8  S000009  2022-01-01         D001
9  S000010  2022-01-01         D001

In [37]:
# Generate transaction dates within each month

month_start = transaction_base["TargetMonth"]

next_month = month_start + pd.offsets.MonthBegin(1)

days_in_month = (
    next_month - month_start
).dt.days

random_days = np.random.randint(
    0,
    days_in_month
)

transaction_base["SalesDate"] = (
    month_start
    + pd.to_timedelta(random_days, unit="D")
)

transaction_base["SalesYear"] = (
    transaction_base["SalesDate"].dt.year
)

transaction_base["SalesMonth"] = (
    transaction_base["SalesDate"].dt.month
)

print("Transaction dates generated successfully.")

display(
    transaction_base[
        [
            "SalesID",
            "SalesDate",
            "SalesYear",
            "SalesMonth",
            "DealershipID"
        ]
    ].head(10)
)

Transaction dates generated successfully.

   SalesID  SalesDate  SalesYear  SalesMonth DealershipID
0  S000001 2022-01-19       2022           1         D001
1  S000002 2022-01-26       2022           1         D001
2  S000003 2022-01-13       2022           1         D001
3  S000004 2022-01-15       2022           1         D001
4  S000005 2022-01-16       2022           1         D001
5  S000006 2022-01-20       2022           1         D001
6  S000007 2022-01-01       2022           1         D001
7  S000008 2022-01-21       2022           1         D001
8  S000009 2022-01-16       2022           1         D001
9  S000010 2022-01-28       2022           1         D001

In [38]:
# Assign customers to transactions

transaction_base["CustomerID"] = np.random.choice(
    customers["CustomerID"].values,
    size=len(transaction_base),
    replace=True
)

print("Customers assigned to transactions.")

print(
    f"Unique customers with transactions: "
    f"{transaction_base['CustomerID'].nunique():,}"
)

display(
    transaction_base[
        [
            "SalesID",
            "SalesDate",
            "DealershipID",
            "CustomerID"
        ]
    ].head(10)
)

Customers assigned to transactions.
Unique customers with transactions: 123,258

   SalesID  SalesDate DealershipID CustomerID
0  S000001 2022-01-19         D001    C001750
1  S000002 2022-01-26         D001    C094037
2  S000003 2022-01-13         D001    C064793
3  S000004 2022-01-15         D001    C042989
4  S000005 2022-01-16         D001    C028920
5  S000006 2022-01-20         D001    C097236
6  S000007 2022-01-01         D001    C098478
7  S000008 2022-01-21         D001    C076117
8  S000009 2022-01-16         D001    C113180
9  S000010 2022-01-28         D001    C009811

In [39]:
# Assign salespeople within their dealership

salesperson_lookup = {
    dealership_id: group["SalespersonID"].values
    for dealership_id, group in salespeople.groupby("DealershipID")
}

transaction_base["SalespersonID"] = transaction_base["DealershipID"].map(
    salesperson_lookup
)

transaction_base["SalespersonID"] = transaction_base.apply(
    lambda row: np.random.choice(row["SalespersonID"]),
    axis=1
)

print("Salespeople assigned to transactions.")

print(
    f"Unique salespeople with transactions: "
    f"{transaction_base['SalespersonID'].nunique()}"
)

display(
    transaction_base[
        [
            "SalesID",
            "SalesDate",
            "DealershipID",
            "CustomerID",
            "SalespersonID"
        ]
    ].head(10)
)

Salespeople assigned to transactions.
Unique salespeople with transactions: 80

   SalesID  SalesDate DealershipID CustomerID SalespersonID
0  S000001 2022-01-19         D001    C001750         SP005
1  S000002 2022-01-26         D001    C094037         SP007
2  S000003 2022-01-13         D001    C064793         SP008
3  S000004 2022-01-15         D001    C042989         SP006
4  S000005 2022-01-16         D001    C028920         SP008
5  S000006 2022-01-20         D001    C097236         SP006
6  S000007 2022-01-01         D001    C098478         SP007
7  S000008 2022-01-21         D001    C076117         SP004
8  S000009 2022-01-16         D001    C113180         SP004
9  S000010 2022-01-28         D001    C009811         SP004

In [40]:
# Bring customer and salesperson attributes into transactions

transaction_base = transaction_base.merge(
    customers[
        [
            "CustomerID",
            "Province",
            "CustomerSegment"
        ]
    ],
    on="CustomerID",
    how="left"
)

transaction_base = transaction_base.merge(
    salespeople[
        [
            "SalespersonID",
            "SalesTeam",
            "PerformanceWeight"
        ]
    ],
    on="SalespersonID",
    how="left"
)

print("Customer and salesperson attributes added.")

display(
    transaction_base[
        [
            "SalesID",
            "DealershipID",
            "CustomerID",
            "Province",
            "CustomerSegment",
            "SalespersonID",
            "SalesTeam",
            "PerformanceWeight"
        ]
    ].head(10)
)

Customer and salesperson attributes added.

,SalesID,DealershipID,CustomerID,Province,CustomerSegment,SalespersonID,SalesTeam,PerformanceWeight
0,S000001,D001,C001750,Alberta,Retail,SP005,Retail,0.980149
1,S000002,D001,C094037,Ontario,Retail,SP007,Commercial,1.189347
2,S000003,D001,C064793,Ontario,Retail,SP008,Fleet,1.371836
3,S000004,D001,C042989,Alberta,Commercial,SP006,Retail,0.930941
4,S000005,D001,C028920,British Columbia,Retail,SP008,Fleet,1.371836
5,S000006,D001,C097236,Ontario,Retail,SP006,Retail,0.930941
6,S000007,D001,C098478,British Columbia,Premium,SP007,Commercial,1.189347
7,S000008,D001,C076117,British Columbia,Commercial,SP004,Retail,1.006429
8,S000009,D001,C113180,British Columbia,Retail,SP004,Retail,1.006429
9,S000010,D001,C009811,British Columbia,Commercial,SP004,Retail,1.006429

In [41]:
# Create vehicle selection probability lookup

vehicle_types = list(vehicle_type_weights.keys())

print("Vehicle selection framework ready:")
print(vehicle_types)

Vehicle selection framework ready:
['Passenger Car', 'SUV', 'Truck', 'Van']

In [42]:
# Build vehicle-type probability function

def get_vehicle_type_weights(province, customer_segment, sales_team):

    province_weights = regional_vehicle_weights[province]

    segment_weights = segment_vehicle_weights[customer_segment]

    team_weights = sales_team_vehicle_weights[sales_team]

    combined_weights = {}

    for vehicle_type in vehicle_types:

        combined_weights[vehicle_type] = (
            province_weights[vehicle_type]
            * segment_weights[vehicle_type]
            * team_weights[vehicle_type]
        )

    total_weight = sum(combined_weights.values())

    normalized_weights = {
        vehicle_type: weight / total_weight
        for vehicle_type, weight in combined_weights.items()
    }

    return normalized_weights


# Test the function with one example

test_weights = get_vehicle_type_weights(
    province="Ontario",
    customer_segment="Retail",
    sales_team="Retail"
)

print("Example vehicle-type probabilities:\n")

for vehicle_type, probability in test_weights.items():
    print(f"{vehicle_type}: {probability:.2%}")

print(f"\nTotal: {sum(test_weights.values()):.2%}")

Example vehicle-type probabilities:

Passenger Car: 48.70%
SUV: 50.79%
Truck: 0.44%
Van: 0.07%

Total: 100.00%

In [43]:
# Test vehicle probabilities across different business scenarios

test_scenarios = [
    ("Ontario", "Retail", "Retail"),
    ("Alberta", "Retail", "Retail"),
    ("Alberta", "Commercial", "Commercial"),
    ("Ontario", "Fleet", "Fleet"),
    ("British Columbia", "Premium", "Retail")
]

for province, segment, team in test_scenarios:

    weights = get_vehicle_type_weights(
        province,
        segment,
        team
    )

    print(
        f"\n{province} | {segment} Customer | {team} Sales"
    )

    for vehicle_type, probability in weights.items():
        print(f"{vehicle_type}: {probability:.2%}")

    print(f"Total: {sum(weights.values()):.2%}")

Ontario | Retail Customer | Retail Sales
Passenger Car: 48.70%
SUV: 50.79%
Truck: 0.44%
Van: 0.07%
Total: 100.00%

Alberta | Retail Customer | Retail Sales
Passenger Car: 40.11%
SUV: 59.03%
Truck: 0.78%
Van: 0.08%
Total: 100.00%

Alberta | Commercial Customer | Commercial Sales
Passenger Car: 7.84%
SUV: 43.88%
Truck: 41.14%
Van: 7.14%
Total: 100.00%

Ontario | Fleet Customer | Fleet Sales
Passenger Car: 17.34%
SUV: 67.45%
Truck: 11.36%
Van: 3.85%
Total: 100.00%

British Columbia | Premium Customer | Retail Sales
Passenger Car: 39.36%
SUV: 60.32%
Truck: 0.27%
Van: 0.05%
Total: 100.00%

In [44]:
# Build balanced vehicle-type probability function

def get_vehicle_type_weights(province, customer_segment, sales_team):

    province_weights = regional_vehicle_weights[province]
    segment_weights = segment_vehicle_weights[customer_segment]
    team_weights = sales_team_vehicle_weights[sales_team]

    combined_weights = {}

    for vehicle_type in vehicle_types:

        combined_weights[vehicle_type] = (
            0.40 * province_weights[vehicle_type]
            + 0.35 * segment_weights[vehicle_type]
            + 0.25 * team_weights[vehicle_type]
        )

    total_weight = sum(combined_weights.values())

    normalized_weights = {
        vehicle_type: weight / total_weight
        for vehicle_type, weight in combined_weights.items()
    }

    return normalized_weights


# Test the balanced model

test_weights = get_vehicle_type_weights(
    province="Ontario",
    customer_segment="Retail",
    sales_team="Retail"
)

print("Balanced vehicle-type probabilities:\n")

for vehicle_type, probability in test_weights.items():
    print(f"{vehicle_type}: {probability:.2%}")

print(f"\nTotal: {sum(test_weights.values()):.2%}")

Balanced vehicle-type probabilities:

Passenger Car: 42.60%
SUV: 43.00%
Truck: 9.20%
Van: 5.20%

Total: 100.00%

In [45]:
# Test balanced vehicle probabilities across scenarios

for province, segment, team in test_scenarios:

    weights = get_vehicle_type_weights(
        province,
        segment,
        team
    )

    print(
        f"\n{province} | {segment} Customer | {team} Sales"
    )

    for vehicle_type, probability in weights.items():
        print(f"{vehicle_type}: {probability:.2%}")

    print(f"Total: {sum(weights.values()):.2%}")

Ontario | Retail Customer | Retail Sales
Passenger Car: 42.60%
SUV: 43.00%
Truck: 9.20%
Van: 5.20%
Total: 100.00%

Alberta | Retail Customer | Retail Sales
Passenger Car: 38.60%
SUV: 44.20%
Truck: 12.00%
Van: 5.20%
Total: 100.00%

Alberta | Commercial Customer | Commercial Sales
Passenger Car: 20.55%
SUV: 32.20%
Truck: 29.45%
Van: 17.80%
Total: 100.00%

Ontario | Fleet Customer | Fleet Sales
Passenger Car: 27.55%
SUV: 37.00%
Truck: 20.65%
Van: 14.80%
Total: 100.00%

British Columbia | Premium Customer | Retail Sales
Passenger Car: 40.60%
SUV: 46.90%
Truck: 7.65%
Van: 4.85%
Total: 100.00%

In [46]:
# Create vehicle lookup by vehicle type

vehicles_by_type = {
    vehicle_type: group["VehicleID"].values
    for vehicle_type, group in vehicles.groupby("VehicleType")
}

for vehicle_type, vehicle_ids in vehicles_by_type.items():
    print(
        f"{vehicle_type}: "
        f"{len(vehicle_ids)} models"
    )

Passenger Car: 9 models
SUV: 9 models
Truck: 4 models
Van: 3 models

In [47]:
# Create model lookup with demand weights

vehicle_model_lookup = {}

for vehicle_type, group in vehicles.groupby("VehicleType"):

    vehicle_ids = group["VehicleID"].values
    demand_weights = group["DemandWeight"].values

    normalized_weights = (
        demand_weights / demand_weights.sum()
    )

    vehicle_model_lookup[vehicle_type] = {
        "vehicle_ids": vehicle_ids,
        "weights": normalized_weights
    }

for vehicle_type, lookup in vehicle_model_lookup.items():
    print(
        f"{vehicle_type}: "
        f"{len(lookup['vehicle_ids'])} models | "
        f"Weight total: {lookup['weights'].sum():.2f}"
    )

Passenger Car: 9 models | Weight total: 1.00
SUV: 9 models | Weight total: 1.00
Truck: 4 models | Weight total: 1.00
Van: 3 models | Weight total: 1.00

In [48]:
# Test specific model selection

def select_vehicle_model(vehicle_type):

    lookup = vehicle_model_lookup[vehicle_type]

    return np.random.choice(
        lookup["vehicle_ids"],
        p=lookup["weights"]
    )


# Test each vehicle type

print("Sample model selections:\n")

for vehicle_type in vehicle_types:

    selections = [
        select_vehicle_model(vehicle_type)
        for _ in range(5)
    ]

    print(f"{vehicle_type}: {selections}")

Sample model selections:

Passenger Car: ['V016', 'V016', 'V001', 'V002', 'V006']
SUV: ['V019', 'V003', 'V019', 'V020', 'V014']
Truck: ['V013', 'V011', 'V013', 'V012', 'V011']
Van: ['V024', 'V025', 'V024', 'V024', 'V024']

In [49]:
# Assign vehicle types to all transactions

def select_vehicle_type(province, customer_segment, sales_team):

    weights = get_vehicle_type_weights(
        province,
        customer_segment,
        sales_team
    )

    return np.random.choice(
        vehicle_types,
        p=[weights[vehicle_type] for vehicle_type in vehicle_types]
    )


transaction_base["VehicleType"] = [
    select_vehicle_type(
        province,
        customer_segment,
        sales_team
    )
    for province, customer_segment, sales_team
    in zip(
        transaction_base["Province"],
        transaction_base["CustomerSegment"],
        transaction_base["SalesTeam"]
    )
]

print("Vehicle types assigned.")

print("\nVehicle type distribution:")
print(
    transaction_base["VehicleType"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

display(
    transaction_base[
        [
            "SalesID",
            "Province",
            "CustomerSegment",
            "SalesTeam",
            "VehicleType"
        ]
    ].head(10)
)

Vehicle types assigned.

Vehicle type distribution:
VehicleType
SUV              41.96
Passenger Car    37.67
Truck            12.81
Van               7.56
Name: proportion, dtype: float64

   SalesID          Province CustomerSegment   SalesTeam    VehicleType
0  S000001           Alberta          Retail      Retail            SUV
1  S000002           Ontario          Retail  Commercial  Passenger Car
2  S000003           Ontario          Retail       Fleet            SUV
3  S000004           Alberta      Commercial      Retail            SUV
4  S000005  British Columbia          Retail       Fleet            SUV
5  S000006           Ontario          Retail      Retail  Passenger Car
6  S000007  British Columbia         Premium  Commercial  Passenger Car
7  S000008  British Columbia      Commercial      Retail            SUV
8  S000009  British Columbia          Retail      Retail          Truck
9  S000010  British Columbia      Commercial      Retail            SUV

In [50]:
# Assign specific vehicle models to all transactions

transaction_base["VehicleID"] = [
    select_vehicle_model(vehicle_type)
    for vehicle_type in transaction_base["VehicleType"]
]

print("Specific vehicle models assigned.")

print(
    f"Unique vehicle models sold: "
    f"{transaction_base['VehicleID'].nunique()}"
)

display(
    transaction_base[
        [
            "SalesID",
            "VehicleType",
            "VehicleID"
        ]
    ].head(10)
)

Specific vehicle models assigned.
Unique vehicle models sold: 25

   SalesID    VehicleType VehicleID
0  S000001            SUV      V023
1  S000002  Passenger Car      V007
2  S000003            SUV      V003
3  S000004            SUV      V003
4  S000005            SUV      V008
5  S000006  Passenger Car      V002
6  S000007  Passenger Car      V017
7  S000008            SUV      V008
8  S000009          Truck      V012
9  S000010            SUV      V020

In [51]:
# Bring vehicle attributes into transactions

transaction_base = transaction_base.merge(
    vehicles[
        [
            "VehicleID",
            "Brand",
            "Model",
            "VehicleType",
            "MSRP",
            "DemandWeight",
            "CostRatio",
            "BaseCost"
        ]
    ],
    on=["VehicleID", "VehicleType"],
    how="left"
)

print("Vehicle attributes added.")

print(
    f"Transaction rows: {len(transaction_base):,}"
)

print(
    f"Missing MSRP values: "
    f"{transaction_base['MSRP'].isna().sum()}"
)

display(
    transaction_base[
        [
            "SalesID",
            "VehicleID",
            "Brand",
            "Model",
            "VehicleType",
            "MSRP",
            "BaseCost"
        ]
    ].head(10)
)

Vehicle attributes added.
Transaction rows: 531,482
Missing MSRP values: 0

   SalesID VehicleID      Brand     Model    VehicleType   MSRP  BaseCost
0  S000001      V023  Evergreen       Eco            SUV  31000   24200.0
1  S000002      V007       Apex        A6  Passenger Car  63000   50800.0
2  S000003      V003  Northstar     Crest            SUV  44000   34200.0
3  S000004      V003  Northstar     Crest            SUV  44000   34200.0
4  S000005      V008       Apex        A7            SUV  48000   39000.0
5  S000006      V002  Northstar     Metro  Passenger Car  53000   44800.0
6  S000007      V017   Velocity        V3  Passenger Car  46000   36900.0
7  S000008      V008       Apex        A7            SUV  48000   39000.0
8  S000009      V012     Summit  Frontier          Truck  63000   48500.0
9  S000010      V020   Velocity        V9            SUV  73000   59000.0

In [52]:
# Generate transaction-level actual cost

transaction_base["ActualCost"] = (
    transaction_base["BaseCost"]
    * np.random.uniform(
        COST_VARIATION_MIN,
        COST_VARIATION_MAX,
        len(transaction_base)
    )
).round(-2)

print("Transaction-level costs generated.")

print(
    f"Minimum actual cost: "
    f"${transaction_base['ActualCost'].min():,.0f}"
)

print(
    f"Maximum actual cost: "
    f"${transaction_base['ActualCost'].max():,.0f}"
)

display(
    transaction_base[
        [
            "SalesID",
            "VehicleID",
            "MSRP",
            "BaseCost",
            "ActualCost"
        ]
    ].head(10)
)

Transaction-level costs generated.
Minimum actual cost: $20,300
Maximum actual cost: $61,000

   SalesID VehicleID   MSRP  BaseCost  ActualCost
0  S000001      V023  31000   24200.0     24700.0
1  S000002      V007  63000   50800.0     51500.0
2  S000003      V003  44000   34200.0     34200.0
3  S000004      V003  44000   34200.0     34000.0
4  S000005      V008  48000   39000.0     39300.0
5  S000006      V002  53000   44800.0     44100.0
6  S000007      V017  46000   36900.0     36400.0
7  S000008      V008  48000   39000.0     38600.0
8  S000009      V012  63000   48500.0     48000.0
9  S000010      V020  73000   59000.0     59900.0

In [53]:
# Generate transaction-level base discount

def generate_base_discount(segment):
    rules = discount_rules[segment]

    return np.random.uniform(
        rules["min_discount"],
        rules["max_discount"]
    )


transaction_base["BaseDiscountRate"] = (
    transaction_base["CustomerSegment"]
    .apply(generate_base_discount)
)

print("Base transaction discounts generated.")

print(
    f"Minimum discount: "
    f"{transaction_base['BaseDiscountRate'].min():.2%}"
)

print(
    f"Maximum discount: "
    f"{transaction_base['BaseDiscountRate'].max():.2%}"
)

display(
    transaction_base[
        [
            "SalesID",
            "CustomerSegment",
            "BaseDiscountRate"
        ]
    ].head(10)
)

Base transaction discounts generated.
Minimum discount: 0.00%
Maximum discount: 12.00%

   SalesID CustomerSegment  BaseDiscountRate
0  S000001          Retail          0.032614
1  S000002          Retail          0.015795
2  S000003          Retail          0.042580
3  S000004      Commercial          0.044625
4  S000005          Retail          0.021967
5  S000006          Retail          0.022516
6  S000007         Premium          0.026030
7  S000008      Commercial          0.061470
8  S000009          Retail          0.010192
9  S000010      Commercial          0.070346

In [54]:
# Apply seasonal promotional discount adjustment

promotion_lookup = (
    monthly_framework[
        ["MonthStart", "PromotionAdjustment"]
    ]
    .drop_duplicates("MonthStart")
)

transaction_base = transaction_base.merge(
    promotion_lookup,
    left_on="TargetMonth",
    right_on="MonthStart",
    how="left"
)

transaction_base["FinalDiscountRate"] = (
    transaction_base["BaseDiscountRate"]
    + transaction_base["PromotionAdjustment"]
)

print("Seasonal promotional adjustments applied.")

print(
    f"Minimum final discount: "
    f"{transaction_base['FinalDiscountRate'].min():.2%}"
)

print(
    f"Maximum final discount: "
    f"{transaction_base['FinalDiscountRate'].max():.2%}"
)

display(
    transaction_base[
        [
            "SalesID",
            "SalesDate",
            "CustomerSegment",
            "BaseDiscountRate",
            "PromotionAdjustment",
            "FinalDiscountRate"
        ]
    ].head(10)
)

Seasonal promotional adjustments applied.
Minimum final discount: 0.00%
Maximum final discount: 13.50%

,SalesID,SalesDate,CustomerSegment,BaseDiscountRate,PromotionAdjustment,FinalDiscountRate
0,S000001,2022-01-19,Retail,0.032614,0.0,0.032614
1,S000002,2022-01-26,Retail,0.015795,0.0,0.015795
2,S000003,2022-01-13,Retail,0.042580,0.0,0.042580
3,S000004,2022-01-15,Commercial,0.044625,0.0,0.044625
4,S000005,2022-01-16,Retail,0.021967,0.0,0.021967
5,S000006,2022-01-20,Retail,0.022516,0.0,0.022516
6,S000007,2022-01-01,Premium,0.026030,0.0,0.026030
7,S000008,2022-01-21,Commercial,0.061470,0.0,0.061470
8,S000009,2022-01-16,Retail,0.010192,0.0,0.010192
9,S000010,2022-01-28,Commercial,0.070346,0.0,0.070346

In [55]:
# Generate transaction-level market adjustment

MARKET_ADJUSTMENT_MIN = -0.01
MARKET_ADJUSTMENT_MAX = 0.01

transaction_base["MarketAdjustmentRate"] = np.random.uniform(
    MARKET_ADJUSTMENT_MIN,
    MARKET_ADJUSTMENT_MAX,
    len(transaction_base)
)

print("Market adjustments generated.")

print(
    f"Minimum market adjustment: "
    f"{transaction_base['MarketAdjustmentRate'].min():.2%}"
)

print(
    f"Maximum market adjustment: "
    f"{transaction_base['MarketAdjustmentRate'].max():.2%}"
)

display(
    transaction_base[
        [
            "SalesID",
            "VehicleID",
            "MSRP",
            "MarketAdjustmentRate"
        ]
    ].head(10)
)

Market adjustments generated.
Minimum market adjustment: -1.00%
Maximum market adjustment: 1.00%

   SalesID VehicleID   MSRP  MarketAdjustmentRate
0  S000001      V023  31000             -0.007941
1  S000002      V007  63000              0.002773
2  S000003      V003  44000              0.009450
3  S000004      V003  44000              0.003042
4  S000005      V008  48000              0.005630
5  S000006      V002  53000             -0.003656
6  S000007      V017  46000             -0.004344
7  S000008      V008  48000              0.003606
8  S000009      V012  63000             -0.009066
9  S000010      V020  73000              0.008482

In [56]:
# Calculate final sale price

transaction_base["AdjustedMSRP"] = (
    transaction_base["MSRP"]
    * (1 + transaction_base["MarketAdjustmentRate"])
)

transaction_base["SalePrice"] = (
    transaction_base["AdjustedMSRP"]
    * (1 - transaction_base["FinalDiscountRate"])
).round(-2)

print("Final sale prices calculated.")

print(
    f"Minimum sale price: "
    f"${transaction_base['SalePrice'].min():,.0f}"
)

print(
    f"Maximum sale price: "
    f"${transaction_base['SalePrice'].max():,.0f}"
)

display(
    transaction_base[
        [
            "SalesID",
            "VehicleID",
            "MSRP",
            "MarketAdjustmentRate",
            "FinalDiscountRate",
            "SalePrice"
        ]
    ].head(10)
)

Final sale prices calculated.
Minimum sale price: $22,400
Maximum sale price: $75,700

,SalesID,VehicleID,MSRP,MarketAdjustmentRate,FinalDiscountRate,SalePrice
0,S000001,V023,31000,-0.007941,0.032614,29800.0
1,S000002,V007,63000,0.002773,0.015795,62200.0
2,S000003,V003,44000,0.009450,0.042580,42500.0
3,S000004,V003,44000,0.003042,0.044625,42200.0
4,S000005,V008,48000,0.005630,0.021967,47200.0
5,S000006,V002,53000,-0.003656,0.022516,51600.0
6,S000007,V017,46000,-0.004344,0.026030,44600.0
7,S000008,V008,48000,0.003606,0.061470,45200.0
8,S000009,V012,63000,-0.009066,0.010192,61800.0
9,S000010,V020,73000,0.008482,0.070346,68400.0

In [57]:
# Calculate gross profit and gross margin

transaction_base["GrossProfit"] = (
    transaction_base["SalePrice"]
    - transaction_base["ActualCost"]
)

transaction_base["GrossMarginRate"] = (
    transaction_base["GrossProfit"]
    / transaction_base["SalePrice"]
)

print("Gross profit and margin calculated.")

print(
    f"Minimum gross profit: "
    f"${transaction_base['GrossProfit'].min():,.0f}"
)

print(
    f"Maximum gross profit: "
    f"${transaction_base['GrossProfit'].max():,.0f}"
)

print(
    f"Average gross margin: "
    f"{transaction_base['GrossMarginRate'].mean():.2%}"
)

display(
    transaction_base[
        [
            "SalesID",
            "VehicleID",
            "SalePrice",
            "ActualCost",
            "GrossProfit",
            "GrossMarginRate"
        ]
    ].head(10)
)

Gross profit and margin calculated.
Minimum gross profit: $0
Maximum gross profit: $16,600
Average gross margin: 16.25%

   SalesID VehicleID  SalePrice  ActualCost  GrossProfit  GrossMarginRate
0  S000001      V023    29800.0     24700.0       5100.0         0.171141
1  S000002      V007    62200.0     51500.0      10700.0         0.172026
2  S000003      V003    42500.0     34200.0       8300.0         0.195294
3  S000004      V003    42200.0     34000.0       8200.0         0.194313
4  S000005      V008    47200.0     39300.0       7900.0         0.167373
5  S000006      V002    51600.0     44100.0       7500.0         0.145349
6  S000007      V017    44600.0     36400.0       8200.0         0.183857
7  S000008      V008    45200.0     38600.0       6600.0         0.146018
8  S000009      V012    61800.0     48000.0      13800.0         0.223301
9  S000010      V020    68400.0     59900.0       8500.0         0.124269

In [58]:
# Add transaction quantity and revenue

transaction_base["Quantity"] = 1

transaction_base["Revenue"] = (
    transaction_base["SalePrice"]
    * transaction_base["Quantity"]
)

print("Quantity and revenue calculated.")

print(
    f"Total units sold: "
    f"{transaction_base['Quantity'].sum():,}"
)

print(
    f"Total revenue: "
    f"${transaction_base['Revenue'].sum():,.0f}"
)

display(
    transaction_base[
        [
            "SalesID",
            "VehicleID",
            "Quantity",
            "SalePrice",
            "Revenue",
            "GrossProfit"
        ]
    ].head(10)
)

Quantity and revenue calculated.
Total units sold: 531,482
Total revenue: $27,120,289,700

   SalesID VehicleID  Quantity  SalePrice  Revenue  GrossProfit
0  S000001      V023         1    29800.0  29800.0       5100.0
1  S000002      V007         1    62200.0  62200.0      10700.0
2  S000003      V003         1    42500.0  42500.0       8300.0
3  S000004      V003         1    42200.0  42200.0       8200.0
4  S000005      V008         1    47200.0  47200.0       7900.0
5  S000006      V002         1    51600.0  51600.0       7500.0
6  S000007      V017         1    44600.0  44600.0       8200.0
7  S000008      V008         1    45200.0  45200.0       6600.0
8  S000009      V012         1    61800.0  61800.0      13800.0
9  S000010      V020         1    68400.0  68400.0       8500.0

In [59]:
# Calculate discount amount

transaction_base["DiscountAmount"] = (
    transaction_base["AdjustedMSRP"]
    * transaction_base["FinalDiscountRate"]
).round(-2)

print("Discount amounts calculated.")

print(
    f"Total discount given: "
    f"${transaction_base['DiscountAmount'].sum():,.0f}"
)

print(
    f"Average discount per vehicle: "
    f"${transaction_base['DiscountAmount'].mean():,.0f}"
)

display(
    transaction_base[
        [
            "SalesID",
            "MSRP",
            "AdjustedMSRP",
            "FinalDiscountRate",
            "DiscountAmount",
            "SalePrice"
        ]
    ].head(10)
)

Discount amounts calculated.
Total discount given: $1,121,434,300
Average discount per vehicle: $2,110

   SalesID   MSRP  AdjustedMSRP  FinalDiscountRate  DiscountAmount  SalePrice
0  S000001  31000  30753.838031           0.032614          1000.0    29800.0
1  S000002  63000  63174.691254           0.015795          1000.0    62200.0
2  S000003  44000  44415.806853           0.042580          1900.0    42500.0
3  S000004  44000  44133.840142           0.044625          2000.0    42200.0
4  S000005  48000  48270.221787           0.021967          1100.0    47200.0
5  S000006  53000  52806.254345           0.022516          1200.0    51600.0
6  S000007  46000  45800.186875           0.026030          1200.0    44600.0
7  S000008  48000  48173.079890           0.061470          3000.0    45200.0
8  S000009  63000  62428.870129           0.010192           600.0    61800.0
9  S000010  73000  73619.218044           0.070346          5200.0    68400.0

In [60]:
# Calculate salesperson sales influence

transaction_base["SalesInfluenceWeight"] = (
    transaction_base["PerformanceWeight"]
    * transaction_base["DealershipID"].map(dealership_capacity)
)

print("Salesperson sales influence calculated.")

display(
    transaction_base[
        [
            "SalesID",
            "DealershipID",
            "SalespersonID",
            "PerformanceWeight",
            "SalesInfluenceWeight"
        ]
    ].head(10)
)

Salesperson sales influence calculated.

   SalesID DealershipID SalespersonID  PerformanceWeight  SalesInfluenceWeight
0  S000001         D001         SP005           0.980149              1.127171
1  S000002         D001         SP007           1.189347              1.367749
2  S000003         D001         SP008           1.371836              1.577612
3  S000004         D001         SP006           0.930941              1.070582
4  S000005         D001         SP008           1.371836              1.577612
5  S000006         D001         SP006           0.930941              1.070582
6  S000007         D001         SP007           1.189347              1.367749
7  S000008         D001         SP004           1.006429              1.157393
8  S000009         D001         SP004           1.006429              1.157393
9  S000010         D001         SP004           1.006429              1.157393

In [61]:
# Validate salesperson transaction distribution

salesperson_sales = (
    transaction_base
    .groupby("SalespersonID")
    .agg(
        Transactions=("SalesID", "count"),
        TotalRevenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        AvgGrossMargin=("GrossMarginRate", "mean")
    )
    .reset_index()
)

salesperson_sales = salesperson_sales.merge(
    salespeople[
        [
            "SalespersonID",
            "SalespersonName",
            "DealershipID",
            "SalesTeam",
            "PerformanceTier",
            "PerformanceWeight"
        ]
    ],
    on="SalespersonID",
    how="left"
)

print(f"Salespeople with transactions: {len(salesperson_sales)}")

print(
    f"Minimum transactions per salesperson: "
    f"{salesperson_sales['Transactions'].min():,}"
)

print(
    f"Maximum transactions per salesperson: "
    f"{salesperson_sales['Transactions'].max():,}"
)

display(
    salesperson_sales.sort_values(
        "Transactions",
        ascending=False
    ).head(10)
)

Salespeople with transactions: 80
Minimum transactions per salesperson: 5,302
Maximum transactions per salesperson: 8,291

,SalespersonID,Transactions,TotalRevenue,GrossProfit,AvgGrossMargin,SalespersonName,DealershipID,SalesTeam,PerformanceTier,PerformanceWeight
19,SP020,8291,423492900.0,68112400.0,0.161762,Sarah Clark,D003,Retail,Top Performer,1.361475
21,SP022,8254,418763300.0,67362400.0,0.161952,David Taylor,D003,Retail,Strong Performer,1.105126
16,SP017,8230,418342800.0,67229400.0,0.161775,Matthew King,D003,Retail,Average Performer,0.990685
20,SP021,8135,410579800.0,66053100.0,0.161850,Olivia Walker,D003,Retail,Average Performer,0.905159
22,SP023,8109,416607100.0,68468100.0,0.165096,Alex Morgan,D003,Commercial,Developing,0.852715
23,SP024,8083,416091700.0,67762600.0,0.163721,Lily Hall,D003,Fleet,Strong Performer,1.178984
17,SP018,8066,409987400.0,65873000.0,0.161750,Emily Hall,D003,Retail,Developing,0.798912
18,SP019,8057,409123000.0,65698000.0,0.161483,James Baker,D003,Retail,Top Performer,1.248924
13,SP014,7330,371896300.0,59581800.0,0.161352,Emma Hall,D002,Retail,Average Performer,0.908796
74,SP075,7327,373496100.0,60157700.0,0.162175,Thomas Young,D010,Retail,Strong Performer,1.128938

In [62]:
# Reassign salespeople using performance weights within each dealership

salesperson_lookup_weighted = {}

for dealership_id, group in salespeople.groupby("DealershipID"):

    salesperson_ids = group["SalespersonID"].values
    performance_weights = group["PerformanceWeight"].values

    normalized_weights = (
        performance_weights / performance_weights.sum()
    )

    salesperson_lookup_weighted[dealership_id] = {
        "SalespersonIDs": salesperson_ids,
        "Weights": normalized_weights
    }


transaction_base["SalespersonID"] = [
    np.random.choice(
        salesperson_lookup_weighted[dealership_id]["SalespersonIDs"],
        p=salesperson_lookup_weighted[dealership_id]["Weights"]
    )
    for dealership_id in transaction_base["DealershipID"]
]

print("Salespeople reassigned using performance weights.")

print(
    f"Unique salespeople with transactions: "
    f"{transaction_base['SalespersonID'].nunique()}"
)

display(
    transaction_base[
        [
            "SalesID",
            "DealershipID",
            "SalespersonID"
        ]
    ].head(10)
)

Salespeople reassigned using performance weights.
Unique salespeople with transactions: 80

   SalesID DealershipID SalespersonID
0  S000001         D001         SP007
1  S000002         D001         SP002
2  S000003         D001         SP004
3  S000004         D001         SP004
4  S000005         D001         SP008
5  S000006         D001         SP008
6  S000007         D001         SP002
7  S000008         D001         SP007
8  S000009         D001         SP002
9  S000010         D001         SP005

In [63]:
# Refresh salesperson attributes after weighted reassignment

transaction_base = transaction_base.drop(
    columns=[
        "SalesTeam",
        "PerformanceWeight",
        "SalesInfluenceWeight"
    ],
    errors="ignore"
)

transaction_base = transaction_base.merge(
    salespeople[
        [
            "SalespersonID",
            "SalesTeam",
            "PerformanceTier",
            "PerformanceWeight"
        ]
    ],
    on="SalespersonID",
    how="left"
)

transaction_base["SalesInfluenceWeight"] = (
    transaction_base["PerformanceWeight"]
    * transaction_base["DealershipID"].map(dealership_capacity)
)

print("Salesperson attributes refreshed.")

print(
    f"Transaction rows: {len(transaction_base):,}"
)

print(
    f"Missing salesperson attributes: "
    f"{transaction_base['PerformanceWeight'].isna().sum()}"
)

display(
    transaction_base[
        [
            "SalesID",
            "DealershipID",
            "SalespersonID",
            "SalesTeam",
            "PerformanceTier",
            "PerformanceWeight",
            "SalesInfluenceWeight"
        ]
    ].head(10)
)

Salesperson attributes refreshed.
Transaction rows: 531,482
Missing salesperson attributes: 0

,SalesID,DealershipID,SalespersonID,SalesTeam,PerformanceTier,PerformanceWeight,SalesInfluenceWeight
0,S000001,D001,SP007,Commercial,Strong Performer,1.189347,1.367749
1,S000002,D001,SP002,Retail,Top Performer,1.271037,1.461693
2,S000003,D001,SP004,Retail,Average Performer,1.006429,1.157393
3,S000004,D001,SP004,Retail,Average Performer,1.006429,1.157393
4,S000005,D001,SP008,Fleet,Top Performer,1.371836,1.577612
5,S000006,D001,SP008,Fleet,Top Performer,1.371836,1.577612
6,S000007,D001,SP002,Retail,Top Performer,1.271037,1.461693
7,S000008,D001,SP007,Commercial,Strong Performer,1.189347,1.367749
8,S000009,D001,SP002,Retail,Top Performer,1.271037,1.461693
9,S000010,D001,SP005,Retail,Average Performer,0.980149,1.127171

In [64]:
# Validate salesperson performance weighting

performance_check = (
    transaction_base
    .groupby("PerformanceTier")
    .agg(
        Transactions=("SalesID", "count"),
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        AvgPerformanceWeight=("PerformanceWeight", "mean")
    )
    .reset_index()
)

performance_check["TransactionShare"] = (
    performance_check["Transactions"]
    / performance_check["Transactions"].sum()
)

performance_check = performance_check.sort_values(
    "AvgPerformanceWeight",
    ascending=False
)

display(performance_check)

,PerformanceTier,Transactions,Revenue,GrossProfit,AvgPerformanceWeight,TransactionShare
3,Top Performer,124474,6.356823e+09,1.026888e+09,1.337714,0.234202
2,Strong Performer,176159,8.988145e+09,1.452367e+09,1.140107,0.331449
0,Average Performer,176668,9.011930e+09,1.457040e+09,0.962411,0.332406
1,Developing,54181,2.763391e+09,4.461137e+08,0.779798,0.101943

In [65]:
# Validate relationship between salesperson performance and transaction volume

salesperson_performance_check = (
    transaction_base
    .groupby("SalespersonID")
    .agg(
        Transactions=("SalesID", "count"),
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum")
    )
    .reset_index()
)

salesperson_performance_check = salesperson_performance_check.merge(
    salespeople[
        [
            "SalespersonID",
            "SalespersonName",
            "DealershipID",
            "PerformanceTier",
            "PerformanceWeight"
        ]
    ],
    on="SalespersonID",
    how="left"
)

print(
    f"Salespeople analyzed: "
    f"{len(salesperson_performance_check)}"
)

print(
    f"Correlation between PerformanceWeight "
    f"and Transactions: "
    f"{salesperson_performance_check['PerformanceWeight'].corr(salesperson_performance_check['Transactions']):.3f}"
)

display(
    salesperson_performance_check[
        [
            "SalespersonID",
            "SalespersonName",
            "DealershipID",
            "PerformanceTier",
            "PerformanceWeight",
            "Transactions",
            "Revenue",
            "GrossProfit"
        ]
    ]
    .sort_values("PerformanceWeight", ascending=False)
    .head(15)
)

Salespeople analyzed: 80
Correlation between PerformanceWeight and Transactions: 0.721

,SalespersonID,SalespersonName,DealershipID,PerformanceTier,PerformanceWeight,Transactions,Revenue,GrossProfit
65,SP066,William Young,D009,Top Performer,1.433637,7720,392498200.0,63407100.0
52,SP053,Michael Brown,D007,Top Performer,1.431058,6662,339146100.0,54706200.0
27,SP028,Chloe King,D004,Top Performer,1.387533,8581,439137000.0,70885500.0
54,SP055,Lily Morgan,D007,Top Performer,1.378727,6454,329493500.0,53320600.0
68,SP069,Alex King,D009,Top Performer,1.372285,7668,391123900.0,63194600.0
7,SP008,Sophia Walker,D001,Top Performer,1.371836,8962,458069600.0,74027300.0
37,SP038,Thomas Martin,D005,Top Performer,1.363900,8636,441275300.0,71637800.0
19,SP020,Sarah Clark,D003,Top Performer,1.361475,10431,530344500.0,85676100.0
49,SP050,Lily Scott,D007,Top Performer,1.352699,6448,330975800.0,53412800.0
53,SP054,Ava Wright,D007,Top Performer,1.350156,6323,322996100.0,52099100.0
40,SP041,Alex Brown,D006,Top Performer,1.329229,7416,379759100.0,61163200.0
48,SP049,Ava Wright,D007,Top Performer,1.311203,6114,312572900.0,50628500.0
1,SP002,James Brown,D001,Top Performer,1.271037,8201,417950700.0,67722700.0
64,SP065,Thomas Morgan,D009,Top Performer,1.254253,6895,353076700.0,56963900.0
18,SP019,James Baker,D003,Top Performer,1.248924,9786,499234600.0,80546200.0

In [66]:
# Comprehensive transaction integrity audit

print("=" * 60)
print("TRANSACTION DATASET INTEGRITY AUDIT")
print("=" * 60)

print(f"\nTotal rows: {len(transaction_base):,}")
print(f"Unique SalesIDs: {transaction_base['SalesID'].nunique():,}")

print("\n--- Missing Values ---")

missing_values = (
    transaction_base.isna()
    .sum()
    .sort_values(ascending=False)
)

display(
    missing_values[missing_values > 0]
)

print("\n--- Duplicate SalesIDs ---")

duplicate_sales_ids = (
    transaction_base["SalesID"]
    .duplicated()
    .sum()
)

print(f"Duplicate SalesIDs: {duplicate_sales_ids:,}")

print("\n--- Date Range ---")

print(
    f"First sale: {transaction_base['SalesDate'].min().date()}"
)

print(
    f"Last sale:  {transaction_base['SalesDate'].max().date()}"
)

print("\n--- Financial Validation ---")

print(
    f"Revenue:      ${transaction_base['Revenue'].sum():,.0f}"
)

print(
    f"Gross Profit: ${transaction_base['GrossProfit'].sum():,.0f}"
)

print(
    f"Avg Margin:   {transaction_base['GrossMarginRate'].mean():.2%}"
)

print("\n--- Discount Validation ---")

print(
    f"Max final discount: "
    f"{transaction_base['FinalDiscountRate'].max():.2%}"
)

print(
    f"Min final discount: "
    f"{transaction_base['FinalDiscountRate'].min():.2%}"
)

print("\n--- Relationship Validation ---")

print(
    f"Customers represented: "
    f"{transaction_base['CustomerID'].nunique():,}"
)

print(
    f"Salespeople represented: "
    f"{transaction_base['SalespersonID'].nunique():,}"
)

print(
    f"Dealerships represented: "
    f"{transaction_base['DealershipID'].nunique():,}"
)

print(
    f"Vehicle models represented: "
    f"{transaction_base['VehicleID'].nunique():,}"
)

print("\n--- Vehicle Type Distribution ---")

display(
    transaction_base["VehicleType"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .rename("Share %")
)

print("\n" + "=" * 60)
print("AUDIT COMPLETE")
print("=" * 60)

============================================================
TRANSACTION DATASET INTEGRITY AUDIT
============================================================

Total rows: 531,482
Unique SalesIDs: 531,482

--- Missing Values ---

Series([], dtype: int64)

--- Duplicate SalesIDs ---
Duplicate SalesIDs: 0

--- Date Range ---
First sale: 2022-01-01
Last sale:  2025-12-31

--- Financial Validation ---
Revenue:      $27,120,289,700
Gross Profit: $4,382,408,900
Avg Margin:   16.25%

--- Discount Validation ---
Max final discount: 13.50%
Min final discount: 0.00%

--- Relationship Validation ---
Customers represented: 123,258
Salespeople represented: 80
Dealerships represented: 10
Vehicle models represented: 25

--- Vehicle Type Distribution ---

VehicleType
SUV              41.96
Passenger Car    37.67
Truck            12.81
Van               7.56
Name: Share %, dtype: float64

============================================================
AUDIT COMPLETE
============================================================

In [67]:
# Assign realistic sales channels

channel_rules = {
    "Retail": {
        "Showroom": 0.65,
        "Online": 0.25,
        "Phone": 0.10
    },
    "Premium": {
        "Showroom": 0.75,
        "Online": 0.15,
        "Phone": 0.10
    },
    "Commercial": {
        "Showroom": 0.35,
        "Online": 0.10,
        "Phone": 0.55
    },
    "Fleet": {
        "Showroom": 0.20,
        "Online": 0.05,
        "Phone": 0.20,
        "Corporate": 0.55
    }
}

def select_sales_channel(segment):

    channels = list(channel_rules[segment].keys())
    probabilities = list(channel_rules[segment].values())

    return np.random.choice(
        channels,
        p=probabilities
    )


transaction_base["SalesChannel"] = [
    select_sales_channel(segment)
    for segment in transaction_base["CustomerSegment"]
]

print("Sales channels assigned.")

print("\nOverall channel distribution:")
print(
    transaction_base["SalesChannel"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nChannel distribution by customer segment:")
display(
    pd.crosstab(
        transaction_base["CustomerSegment"],
        transaction_base["SalesChannel"],
        normalize="index"
    )
    .mul(100)
    .round(2)
)

Sales channels assigned.

Overall channel distribution:
SalesChannel
Showroom     59.34
Online       20.09
Phone        16.15
Corporate     4.41
Name: proportion, dtype: float64

Channel distribution by customer segment:

SalesChannel     Corporate  Online  Phone  Showroom
CustomerSegment
Commercial            0.00    9.97  55.16     34.87
Fleet                54.99    4.86  20.17     19.97
Premium               0.00   15.01  10.18     74.82
Retail                0.00   24.98   9.99     65.02

In [68]:
# Assign realistic payment methods

payment_rules = {
    "Retail": {
        "Financing": 0.55,
        "Cash": 0.25,
        "Lease": 0.20
    },
    "Premium": {
        "Financing": 0.45,
        "Lease": 0.35,
        "Cash": 0.20
    },
    "Commercial": {
        "Financing": 0.50,
        "Cash": 0.30,
        "Lease": 0.20
    },
    "Fleet": {
        "Financing": 0.45,
        "Lease": 0.45,
        "Cash": 0.10
    }
}

def select_payment_method(segment):

    methods = list(payment_rules[segment].keys())
    probabilities = list(payment_rules[segment].values())

    return np.random.choice(
        methods,
        p=probabilities
    )


transaction_base["PaymentMethod"] = [
    select_payment_method(segment)
    for segment in transaction_base["CustomerSegment"]
]

print("Payment methods assigned.")

print("\nOverall payment method distribution:")
print(
    transaction_base["PaymentMethod"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nPayment method distribution by customer segment:")
display(
    pd.crosstab(
        transaction_base["CustomerSegment"],
        transaction_base["PaymentMethod"],
        normalize="index"
    )
    .mul(100)
    .round(2)
)

Payment methods assigned.

Overall payment method distribution:
PaymentMethod
Financing    52.02
Lease        24.31
Cash         23.67
Name: proportion, dtype: float64

Payment method distribution by customer segment:

PaymentMethod     Cash  Financing  Lease
CustomerSegment
Commercial       30.28      49.82  19.91
Fleet            10.01      44.58  45.41
Premium          19.77      45.01  35.22
Retail           25.07      54.97  19.96

In [69]:
# Assign payment term

def select_payment_term(payment_method):

    if payment_method == "Cash":
        return 0

    elif payment_method == "Financing":
        return np.random.choice(
            [36, 48, 60, 72],
            p=[0.15, 0.30, 0.40, 0.15]
        )

    elif payment_method == "Lease":
        return np.random.choice(
            [24, 36, 48],
            p=[0.25, 0.55, 0.20]
        )


transaction_base["PaymentTermMonths"] = [
    select_payment_term(payment_method)
    for payment_method in transaction_base["PaymentMethod"]
]

print("Payment terms assigned.")

print("\nOverall payment term distribution:")
print(
    transaction_base["PaymentTermMonths"]
    .value_counts()
    .sort_index()
)

print("\nPayment term by payment method:")
display(
    transaction_base
    .groupby("PaymentMethod")["PaymentTermMonths"]
    .agg(
        Count="count",
        AverageTerm="mean",
        MinimumTerm="min",
        MaximumTerm="max"
    )
    .round(2)
)

Payment terms assigned.

Overall payment term distribution:
PaymentTermMonths
0     125825
24     32276
36    112629
48    108749
60    110710
72     41293
Name: count, dtype: int64

Payment term by payment method:

                Count  AverageTerm  MinimumTerm  MaximumTerm
PaymentMethod
Cash           125825         0.00            0            0
Financing      276480        54.59           36           72
Lease          129177        35.40           24           48

In [70]:
# Add customer registration date and calculate tenure

transaction_base = transaction_base.merge(
    customers[
        [
            "CustomerID",
            "RegistrationDate"
        ]
    ],
    on="CustomerID",
    how="left"
)

transaction_base["CustomerTenureMonths"] = (
    (
        transaction_base["SalesDate"].dt.year
        - transaction_base["RegistrationDate"].dt.year
    ) * 12
    +
    (
        transaction_base["SalesDate"].dt.month
        - transaction_base["RegistrationDate"].dt.month
    )
)

transaction_base["CustomerTenureMonths"] = (
    transaction_base["CustomerTenureMonths"]
    .clip(lower=0)
)

print("Customer tenure calculated.")

print(
    f"Minimum tenure: "
    f"{transaction_base['CustomerTenureMonths'].min()} months"
)

print(
    f"Maximum tenure: "
    f"{transaction_base['CustomerTenureMonths'].max()} months"
)

print(
    f"Average tenure: "
    f"{transaction_base['CustomerTenureMonths'].mean():.1f} months"
)

display(
    transaction_base[
        [
            "SalesID",
            "CustomerID",
            "RegistrationDate",
            "SalesDate",
            "CustomerTenureMonths"
        ]
    ].head(10)
)

Customer tenure calculated.
Minimum tenure: 0 months
Maximum tenure: 71 months
Average tenure: 18.0 months

   SalesID CustomerID RegistrationDate  SalesDate  CustomerTenureMonths
0  S000001    C001750       2024-01-07 2022-01-19                     0
1  S000002    C094037       2025-08-29 2022-01-26                     0
2  S000003    C064793       2021-10-09 2022-01-13                     3
3  S000004    C042989       2020-05-22 2022-01-15                    20
4  S000005    C028920       2021-12-22 2022-01-16                     1
5  S000006    C097236       2023-01-09 2022-01-20                     0
6  S000007    C098478       2025-06-28 2022-01-01                     0
7  S000008    C076117       2025-08-09 2022-01-21                     0
8  S000009    C113180       2022-09-08 2022-01-16                     0
9  S000010    C009811       2023-09-21 2022-01-28                     0

In [71]:
# Correct customer registration dates for transaction consistency

customer_first_sale = (
    transaction_base
    .groupby("CustomerID")["SalesDate"]
    .min()
    .reset_index()
    .rename(columns={"SalesDate": "FirstSaleDate"})
)

transaction_base = transaction_base.drop(
    columns=["RegistrationDate", "CustomerTenureMonths"],
    errors="ignore"
)

transaction_base = transaction_base.merge(
    customer_first_sale,
    on="CustomerID",
    how="left"
)

# Customers must be registered before their first transaction.
# Generate a realistic registration date 1–36 months before first sale.

registration_offset_days = np.random.randint(
    30,
    1095,
    len(transaction_base)
)

transaction_base["RegistrationDate"] = (
    transaction_base["FirstSaleDate"]
    - pd.to_timedelta(
        registration_offset_days,
        unit="D"
    )
)

transaction_base["CustomerTenureMonths"] = (
    (
        transaction_base["SalesDate"].dt.year
        - transaction_base["RegistrationDate"].dt.year
    ) * 12
    +
    (
        transaction_base["SalesDate"].dt.month
        - transaction_base["RegistrationDate"].dt.month
    )
).clip(lower=0)

# Remove helper column
transaction_base = transaction_base.drop(
    columns=["FirstSaleDate"]
)

print("Customer registration dates corrected.")

print(
    f"Minimum tenure: "
    f"{transaction_base['CustomerTenureMonths'].min()} months"
)

print(
    f"Maximum tenure: "
    f"{transaction_base['CustomerTenureMonths'].max()} months"
)

print(
    f"Average tenure: "
    f"{transaction_base['CustomerTenureMonths'].mean():.1f} months"
)

print(
    "Invalid registration dates: "
    f"{(transaction_base['RegistrationDate'] > transaction_base['SalesDate']).sum():,}"
)

display(
    transaction_base[
        [
            "SalesID",
            "CustomerID",
            "RegistrationDate",
            "SalesDate",
            "CustomerTenureMonths"
        ]
    ].head(10)
)

Customer registration dates corrected.
Minimum tenure: 0 months
Maximum tenure: 83 months
Average tenure: 34.0 months
Invalid registration dates: 0

   SalesID CustomerID RegistrationDate  SalesDate  CustomerTenureMonths
0  S000001    C001750       2019-03-21 2022-01-19                    34
1  S000002    C094037       2020-05-30 2022-01-26                    20
2  S000003    C064793       2020-01-05 2022-01-13                    24
3  S000004    C042989       2020-12-27 2022-01-15                    13
4  S000005    C028920       2019-01-18 2022-01-16                    36
5  S000006    C097236       2021-04-05 2022-01-20                     9
6  S000007    C098478       2021-08-05 2022-01-01                     5
7  S000008    C076117       2021-10-29 2022-01-21                     3
8  S000009    C113180       2019-07-05 2022-01-16                    30
9  S000010    C009811       2021-12-02 2022-01-28                     1

In [72]:
# Create customer lifecycle bands

def tenure_band(months):

    if months <= 6:
        return "New"

    elif months <= 12:
        return "Recent"

    elif months <= 24:
        return "Established"

    elif months <= 48:
        return "Loyal"

    else:
        return "Long-Term"


transaction_base["CustomerTenureBand"] = (
    transaction_base["CustomerTenureMonths"]
    .apply(tenure_band)
)

print("Customer tenure bands assigned.")

print("\nTenure band distribution:")

display(
    transaction_base["CustomerTenureBand"]
    .value_counts()
    .rename_axis("CustomerTenureBand")
    .to_frame("Transactions")
)

print("\nTenure band percentage:")

display(
    transaction_base["CustomerTenureBand"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .rename("Share %")
)

Customer tenure bands assigned.

Tenure band distribution:

                    Transactions
CustomerTenureBand
Loyal                     253379
Long-Term                 113347
Established               104849
Recent                     36183
New                        23724

Tenure band percentage:

CustomerTenureBand
Loyal          47.67
Long-Term      21.33
Established    19.73
Recent          6.81
New             4.46
Name: Share %, dtype: float64

In [73]:
# Identify first-time vs repeat customer purchases

transaction_base = transaction_base.sort_values(
    ["CustomerID", "SalesDate", "SalesID"]
).copy()

transaction_base["CustomerPurchaseNumber"] = (
    transaction_base
    .groupby("CustomerID")
    .cumcount()
    + 1
)

transaction_base["CustomerPurchaseType"] = np.where(
    transaction_base["CustomerPurchaseNumber"] == 1,
    "First Purchase",
    "Repeat Purchase"
)

print("Customer purchase history calculated.")

print("\nPurchase type distribution:")

display(
    transaction_base["CustomerPurchaseType"]
    .value_counts()
    .rename_axis("CustomerPurchaseType")
    .to_frame("Transactions")
)

print("\nUnique customers:")
print(
    f"{transaction_base['CustomerID'].nunique():,}"
)

print("\nRepeat-purchase transactions:")
print(
    f"{(transaction_base['CustomerPurchaseNumber'] > 1).sum():,}"
)

display(
    transaction_base[
        [
            "SalesID",
            "CustomerID",
            "SalesDate",
            "CustomerPurchaseNumber",
            "CustomerPurchaseType"
        ]
    ].head(15)
)

Customer purchase history calculated.

Purchase type distribution:

                      Transactions
CustomerPurchaseType
Repeat Purchase             408224
First Purchase              123258

Unique customers:
123,258

Repeat-purchase transactions:
408,224

,SalesID,CustomerID,SalesDate,CustomerPurchaseNumber,CustomerPurchaseType
3092,S003093,C000001,2022-04-18,1,First Purchase
125508,S125509,C000001,2022-10-03,2,Repeat Purchase
245456,S245457,C000001,2023-03-26,3,Repeat Purchase
254672,S254673,C000001,2023-11-14,4,Repeat Purchase
146954,S146955,C000001,2024-03-30,5,Repeat Purchase
414572,S414573,C000001,2025-04-21,6,Repeat Purchase
242573,S242574,C000002,2022-12-11,1,First Purchase
97862,S097863,C000002,2025-01-18,2,Repeat Purchase
320067,S320068,C000002,2025-07-02,3,Repeat Purchase
474473,S474474,C000003,2022-02-05,1,First Purchase
344169,S344170,C000003,2023-09-15,2,Repeat Purchase
393913,S393914,C000003,2023-10-10,3,Repeat Purchase
310038,S310039,C000003,2024-08-30,4,Repeat Purchase
315610,S315611,C000003,2025-02-19,5,Repeat Purchase
444623,S444624,C000004,2023-09-23,1,First Purchase

In [74]:
# Calculate days between customer purchases

transaction_base = transaction_base.sort_values(
    ["CustomerID", "SalesDate", "SalesID"]
).copy()

transaction_base["PreviousPurchaseDate"] = (
    transaction_base
    .groupby("CustomerID")["SalesDate"]
    .shift(1)
)

transaction_base["DaysSincePreviousPurchase"] = (
    transaction_base["SalesDate"]
    - transaction_base["PreviousPurchaseDate"]
).dt.days

print("Purchase interval calculated.")

print(
    f"First-purchase records without previous date: "
    f"{transaction_base['DaysSincePreviousPurchase'].isna().sum():,}"
)

print(
    f"Minimum repeat purchase interval: "
    f"{transaction_base['DaysSincePreviousPurchase'].min():.0f} days"
)

print(
    f"Maximum repeat purchase interval: "
    f"{transaction_base['DaysSincePreviousPurchase'].max():.0f} days"
)

print(
    f"Average repeat purchase interval: "
    f"{transaction_base['DaysSincePreviousPurchase'].mean():.1f} days"
)

display(
    transaction_base[
        [
            "SalesID",
            "CustomerID",
            "SalesDate",
            "CustomerPurchaseNumber",
            "PreviousPurchaseDate",
            "DaysSincePreviousPurchase"
        ]
    ].head(15)
)

Purchase interval calculated.
First-purchase records without previous date: 123,258
Minimum repeat purchase interval: 0 days
Maximum repeat purchase interval: 1448 days
Average repeat purchase interval: 246.2 days

,SalesID,CustomerID,SalesDate,CustomerPurchaseNumber,PreviousPurchaseDate,DaysSincePreviousPurchase
3092,S003093,C000001,2022-04-18,1,NaT,NaN
125508,S125509,C000001,2022-10-03,2,2022-04-18,168.0
245456,S245457,C000001,2023-03-26,3,2022-10-03,174.0
254672,S254673,C000001,2023-11-14,4,2023-03-26,233.0
146954,S146955,C000001,2024-03-30,5,2023-11-14,137.0
414572,S414573,C000001,2025-04-21,6,2024-03-30,387.0
242573,S242574,C000002,2022-12-11,1,NaT,NaN
97862,S097863,C000002,2025-01-18,2,2022-12-11,769.0
320067,S320068,C000002,2025-07-02,3,2025-01-18,165.0
474473,S474474,C000003,2022-02-05,1,NaT,NaN
344169,S344170,C000003,2023-09-15,2,2022-02-05,587.0
393913,S393914,C000003,2023-10-10,3,2023-09-15,25.0
310038,S310039,C000003,2024-08-30,4,2023-10-10,325.0
315610,S315611,C000003,2025-02-19,5,2024-08-30,173.0
444623,S444624,C000004,2023-09-23,1,NaT,NaN

In [75]:
# Create customer purchase-frequency bands

def purchase_interval_band(days):

    if pd.isna(days):
        return "First Purchase"

    elif days <= 90:
        return "0-90 Days"

    elif days <= 180:
        return "91-180 Days"

    elif days <= 365:
        return "181-365 Days"

    elif days <= 730:
        return "1-2 Years"

    else:
        return "2+ Years"


transaction_base["PurchaseIntervalBand"] = (
    transaction_base["DaysSincePreviousPurchase"]
    .apply(purchase_interval_band)
)

print("Purchase interval bands assigned.")

display(
    transaction_base["PurchaseIntervalBand"]
    .value_counts()
    .rename_axis("PurchaseIntervalBand")
    .to_frame("Transactions")
)

print("\nPurchase interval percentage:")

display(
    transaction_base["PurchaseIntervalBand"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .rename("Share %")
)

Purchase interval bands assigned.

                      Transactions
PurchaseIntervalBand
First Purchase              123258
0-90 Days                   120020
181-365 Days                106401
91-180 Days                  85601
1-2 Years                    77239
2+ Years                     18963

Purchase interval percentage:

PurchaseIntervalBand
First Purchase    23.19
0-90 Days         22.58
181-365 Days      20.02
91-180 Days       16.11
1-2 Years         14.53
2+ Years           3.57
Name: Share %, dtype: float64

In [76]:
# Add transaction calendar attributes

transaction_base["SalesYear"] = transaction_base["SalesDate"].dt.year

transaction_base["SalesMonthNumber"] = (
    transaction_base["SalesDate"].dt.month
)

transaction_base["SalesMonthName"] = (
    transaction_base["SalesDate"].dt.month_name()
)

transaction_base["SalesQuarter"] = (
    "Q"
    + transaction_base["SalesDate"].dt.quarter.astype(str)
)

transaction_base["SalesYearMonth"] = (
    transaction_base["SalesDate"].dt.strftime("%Y-%m")
)

transaction_base["SalesYearQuarter"] = (
    transaction_base["SalesYear"].astype(str)
    + "-Q"
    + transaction_base["SalesDate"].dt.quarter.astype(str)
)

print("Transaction calendar attributes added.")

display(
    transaction_base[
        [
            "SalesID",
            "SalesDate",
            "SalesYear",
            "SalesMonthNumber",
            "SalesMonthName",
            "SalesQuarter",
            "SalesYearMonth",
            "SalesYearQuarter"
        ]
    ].head(10)
)

Transaction calendar attributes added.

,SalesID,SalesDate,SalesYear,SalesMonthNumber,SalesMonthName,SalesQuarter,SalesYearMonth,SalesYearQuarter
3092,S003093,2022-04-18,2022,4,April,Q2,2022-04,2022-Q2
125508,S125509,2022-10-03,2022,10,October,Q4,2022-10,2022-Q4
245456,S245457,2023-03-26,2023,3,March,Q1,2023-03,2023-Q1
254672,S254673,2023-11-14,2023,11,November,Q4,2023-11,2023-Q4
146954,S146955,2024-03-30,2024,3,March,Q1,2024-03,2024-Q1
414572,S414573,2025-04-21,2025,4,April,Q2,2025-04,2025-Q2
242573,S242574,2022-12-11,2022,12,December,Q4,2022-12,2022-Q4
97862,S097863,2025-01-18,2025,1,January,Q1,2025-01,2025-Q1
320067,S320068,2025-07-02,2025,7,July,Q3,2025-07,2025-Q3
474473,S474474,2022-02-05,2022,2,February,Q1,2022-02,2022-Q1

In [77]:
# Add annual growth factor to transactions

growth_factor_map = {
    2022: 1.00,
    2023: 1.06,
    2024: 1.11,
    2025: 1.17
}

transaction_base["GrowthFactor"] = (
    transaction_base["SalesYear"]
    .map(growth_factor_map)
)

print("Annual growth factors added.")

print("\nGrowth factor by year:")

display(
    transaction_base[
        [
            "SalesYear",
            "GrowthFactor"
        ]
    ]
    .drop_duplicates()
    .sort_values("SalesYear")
)

Annual growth factors added.

Growth factor by year:

        SalesYear  GrowthFactor
3092         2022          1.00
245456       2023          1.06
146954       2024          1.11
414572       2025          1.17

In [78]:
# Add monthly seasonality factor to transactions

seasonality_lookup = (
    monthly_framework[
        ["MonthStart", "SeasonalityFactor"]
    ]
    .drop_duplicates("MonthStart")
)

transaction_base["MonthStart"] = (
    transaction_base["SalesDate"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

transaction_base = transaction_base.merge(
    seasonality_lookup,
    on="MonthStart",
    how="left"
)

print("Seasonality factors added.")

print(
    f"Missing seasonality factors: "
    f"{transaction_base['SeasonalityFactor'].isna().sum():,}"
)

display(
    transaction_base[
        [
            "SalesID",
            "SalesDate",
            "MonthStart",
            "SalesMonthName",
            "SeasonalityFactor"
        ]
    ].head(10)
)

Seasonality factors added.
Missing seasonality factors: 0

   SalesID  SalesDate MonthStart SalesMonthName  SeasonalityFactor
0  S003093 2022-04-18 2022-04-01          April               1.00
1  S125509 2022-10-03 2022-10-01        October               1.02
2  S245457 2023-03-26 2023-03-01          March               0.95
3  S254673 2023-11-14 2023-11-01       November               1.12
4  S146955 2024-03-30 2024-03-01          March               0.95
5  S414573 2025-04-21 2025-04-01          April               1.00
6  S242574 2022-12-11 2022-12-01       December               1.18
7  S097863 2025-01-18 2025-01-01        January               0.85
8  S320068 2025-07-02 2025-07-01           July               1.08
9  S474474 2022-02-05 2022-02-01       February               0.90

In [79]:
# Final pre-freeze transaction validation

print("=" * 60)
print("PRE-FREEZE TRANSACTION VALIDATION")
print("=" * 60)

print(f"\nRows: {len(transaction_base):,}")
print(f"Unique SalesIDs: {transaction_base['SalesID'].nunique():,}")

print(
    f"Duplicate SalesIDs: "
    f"{transaction_base['SalesID'].duplicated().sum():,}"
)

print(
    f"Missing values: "
    f"{transaction_base.isna().sum().sum():,}"
)

print(
    f"Customers: "
    f"{transaction_base['CustomerID'].nunique():,}"
)

print(
    f"Salespeople: "
    f"{transaction_base['SalespersonID'].nunique():,}"
)

print(
    f"Dealerships: "
    f"{transaction_base['DealershipID'].nunique():,}"
)

print(
    f"Vehicle models: "
    f"{transaction_base['VehicleID'].nunique():,}"
)

print(
    f"Total revenue: "
    f"${transaction_base['Revenue'].sum():,.0f}"
)

print(
    f"Total gross profit: "
    f"${transaction_base['GrossProfit'].sum():,.0f}"
)

print(
    f"Average gross margin: "
    f"{transaction_base['GrossMarginRate'].mean():.2%}"
)

print("\n" + "=" * 60)
print("PRE-FREEZE VALIDATION COMPLETE")
print("=" * 60)

============================================================
PRE-FREEZE TRANSACTION VALIDATION
============================================================

Rows: 531,482
Unique SalesIDs: 531,482
Duplicate SalesIDs: 0
Missing values: 246,516
Customers: 123,258
Salespeople: 80
Dealerships: 10
Vehicle models: 25
Total revenue: $27,120,289,700
Total gross profit: $4,382,408,900
Average gross margin: 16.25%

============================================================
PRE-FREEZE VALIDATION COMPLETE
============================================================

In [80]:
# Diagnose missing values before freezing the transaction table

missing_summary = (
    transaction_base.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_summary = missing_summary[
    missing_summary > 0
]

missing_percentage = (
    missing_summary
    / len(transaction_base)
    * 100
).round(2)

missing_report = pd.DataFrame({
    "MissingRows": missing_summary,
    "MissingPercent": missing_percentage
})

print("=" * 70)
print("MISSING VALUE DIAGNOSTIC")
print("=" * 70)

display(missing_report)

print("\nTotal missing cells:")
print(f"{transaction_base.isna().sum().sum():,}")

print("\nColumns with missing values:")
print(len(missing_report))

print("\n" + "=" * 70)
print("DIAGNOSTIC COMPLETE")
print("=" * 70)

======================================================================
MISSING VALUE DIAGNOSTIC
======================================================================

                           MissingRows  MissingPercent
DaysSincePreviousPurchase       123258           23.19
PreviousPurchaseDate            123258           23.19

Total missing cells:
246,516

Columns with missing values:
2

======================================================================
DIAGNOSTIC COMPLETE
======================================================================

In [82]:
# Rebuild DimCustomer with customer-level tenure
# calculated consistently as of the dataset end date.

CUSTOMER_AS_OF_DATE = pd.Timestamp("2025-12-31")

dim_customer = (
    customers[
        [
            "CustomerID",
            "Province",
            "CustomerSegment",
            "RegistrationDate"
        ]
    ]
    .drop_duplicates("CustomerID")
    .copy()
)

# Calculate tenure from registration date to dataset end date
dim_customer["CustomerTenureMonths"] = (
    (
        CUSTOMER_AS_OF_DATE.year
        - dim_customer["RegistrationDate"].dt.year
    ) * 12
    +
    (
        CUSTOMER_AS_OF_DATE.month
        - dim_customer["RegistrationDate"].dt.month
    )
).clip(lower=0)

# Create stable customer lifecycle band
def customer_tenure_band(months):

    if months <= 6:
        return "New"

    elif months <= 12:
        return "Recent"

    elif months <= 24:
        return "Established"

    elif months <= 48:
        return "Loyal"

    else:
        return "Long-Term"


dim_customer["CustomerTenureBand"] = (
    dim_customer["CustomerTenureMonths"]
    .apply(customer_tenure_band)
)

print("DimCustomer rebuilt.")

print(f"Rows: {len(dim_customer):,}")

print(
    f"Unique CustomerIDs: "
    f"{dim_customer['CustomerID'].nunique():,}"
)

print(
    f"Duplicate CustomerIDs: "
    f"{dim_customer['CustomerID'].duplicated().sum():,}"
)

print(
    f"Missing CustomerIDs: "
    f"{dim_customer['CustomerID'].isna().sum():,}"
)

print(
    f"Missing tenure values: "
    f"{dim_customer['CustomerTenureMonths'].isna().sum():,}"
)

print(
    f"Minimum tenure: "
    f"{dim_customer['CustomerTenureMonths'].min():.0f} months"
)

print(
    f"Maximum tenure: "
    f"{dim_customer['CustomerTenureMonths'].max():.0f} months"
)

print(
    f"Average tenure: "
    f"{dim_customer['CustomerTenureMonths'].mean():.1f} months"
)

print("\nCustomer tenure band distribution:")

display(
    dim_customer["CustomerTenureBand"]
    .value_counts()
    .rename_axis("CustomerTenureBand")
    .to_frame("Customers")
)

print("\nSample:")

display(dim_customer.head(10))

DimCustomer rebuilt.
Rows: 125,000
Unique CustomerIDs: 125,000
Duplicate CustomerIDs: 0
Missing CustomerIDs: 0
Missing tenure values: 0
Minimum tenure: 0 months
Maximum tenure: 71 months
Average tenure: 35.4 months

Customer tenure band distribution:

                    Customers
CustomerTenureBand
Loyal                   41560
Long-Term               39725
Established             20939
New                     12352
Recent                  10424

Sample:

,CustomerID,Province,CustomerSegment,RegistrationDate,CustomerTenureMonths,CustomerTenureBand
0,C000001,Ontario,Premium,2020-09-02,63,Long-Term
1,C000002,Ontario,Commercial,2021-06-08,54,Long-Term
2,C000003,Ontario,Retail,2021-02-03,58,Long-Term
3,C000004,Ontario,Retail,2025-06-05,6,New
4,C000005,Ontario,Retail,2024-09-11,15,Established
5,C000006,Ontario,Retail,2024-05-14,19,Established
6,C000007,Ontario,Retail,2020-02-16,70,Long-Term
7,C000008,British Columbia,Premium,2021-10-18,50,Long-Term
8,C000009,Ontario,Retail,2023-02-24,34,Loyal
9,C000010,Ontario,Retail,2023-01-24,35,Loyal

In [83]:
# Create DimVehicle

dim_vehicle = (
    vehicles[
        [
            "VehicleID",
            "Brand",
            "Model",
            "VehicleType",
            "MSRP",
            "CostRatio",
            "BaseCost",
            "DemandWeight"
        ]
    ]
    .drop_duplicates("VehicleID")
    .copy()
)

print("DimVehicle created.")

print(f"Rows: {len(dim_vehicle):,}")

print(
    f"Unique VehicleIDs: "
    f"{dim_vehicle['VehicleID'].nunique():,}"
)

print(
    f"Duplicate VehicleIDs: "
    f"{dim_vehicle['VehicleID'].duplicated().sum():,}"
)

print(
    f"Missing VehicleIDs: "
    f"{dim_vehicle['VehicleID'].isna().sum():,}"
)

print("\nVehicle type distribution:")

display(
    dim_vehicle["VehicleType"]
    .value_counts()
    .rename_axis("VehicleType")
    .to_frame("Models")
)

print("\nDemand weight validation by vehicle type:")

display(
    dim_vehicle
    .groupby("VehicleType")["DemandWeight"]
    .agg(
        ModelCount="count",
        WeightTotal="sum",
        MinimumWeight="min",
        MaximumWeight="max"
    )
    .round(3)
)

print("\nSample:")

display(dim_vehicle.head(10))

DimVehicle created.
Rows: 25
Unique VehicleIDs: 25
Duplicate VehicleIDs: 0
Missing VehicleIDs: 0

Vehicle type distribution:

               Models
VehicleType
Passenger Car       9
SUV                 9
Truck               4
Van                 3

Demand weight validation by vehicle type:

               ModelCount  WeightTotal  MinimumWeight  MaximumWeight
VehicleType
Passenger Car           9         9.35           0.75            1.3
SUV                     9         9.40           0.85            1.2
Truck                   4         3.50           0.65            1.1
Van                     3         2.25           0.70            0.8

Sample:

,VehicleID,Brand,Model,VehicleType,MSRP,CostRatio,BaseCost,DemandWeight
0,V001,Northstar,Nova,Passenger Car,63000,0.844092,53200.0,1.25
1,V002,Northstar,Metro,Passenger Car,53000,0.844571,44800.0,1.05
2,V003,Northstar,Crest,SUV,44000,0.776701,34200.0,1.10
3,V004,Northstar,Horizon,SUV,72000,0.803750,57900.0,1.20
4,V005,Northstar,Titan,Truck,47000,0.800254,37600.0,0.90
5,V006,Apex,A4,Passenger Car,45000,0.835180,37600.0,1.00
6,V007,Apex,A6,Passenger Car,63000,0.806295,50800.0,0.75
7,V008,Apex,A7,SUV,48000,0.813432,39000.0,1.10
8,V009,Apex,A9,SUV,52000,0.786241,40900.0,0.85
9,V010,Apex,X1,Van,45000,0.808684,36400.0,0.70

In [84]:
# Create DimDealership

dim_dealership = (
    dealerships[
        [
            "DealershipID",
            "DealershipName",
            "Province",
            "Region",
            "SalesCapacityWeight"
        ]
    ]
    .drop_duplicates("DealershipID")
    .copy()
)

print("DimDealership created.")

print(f"Rows: {len(dim_dealership):,}")

print(
    f"Unique DealershipIDs: "
    f"{dim_dealership['DealershipID'].nunique():,}"
)

print(
    f"Duplicate DealershipIDs: "
    f"{dim_dealership['DealershipID'].duplicated().sum():,}"
)

print(
    f"Missing DealershipIDs: "
    f"{dim_dealership['DealershipID'].isna().sum():,}"
)

print("\nDealership distribution by province:")

display(
    dim_dealership
    .groupby("Province")
    .agg(
        Dealerships=("DealershipID", "count"),
        CapacityWeight=("SalesCapacityWeight", "sum")
    )
    .round(3)
)

print("\nSample:")

display(dim_dealership)

DimDealership created.
Rows: 10
Unique DealershipIDs: 10
Duplicate DealershipIDs: 0
Missing DealershipIDs: 0

Dealership distribution by province:

                  Dealerships  CapacityWeight
Province
Alberta                     2             2.1
British Columbia            1             1.2
Ontario                     7             7.7

Sample:

,DealershipID,DealershipName,Province,Region,SalesCapacityWeight
0,D001,Dadwal Motors Oakville,Ontario,GTA West,1.15
1,D002,Dadwal Motors Mississauga,Ontario,GTA West,1.20
2,D003,Dadwal Motors Toronto,Ontario,GTA Central,1.35
3,D004,Dadwal Motors Vaughan,Ontario,GTA North,1.10
4,D005,Dadwal Motors Ottawa,Ontario,Eastern Ontario,1.05
5,D006,Dadwal Motors London,Ontario,Southwestern Ontario,0.90
6,D007,Dadwal Motors Kitchener,Ontario,Waterloo Region,0.95
7,D008,Dadwal Motors Calgary,Alberta,Southern Alberta,1.10
8,D009,Dadwal Motors Edmonton,Alberta,Northern Alberta,1.00
9,D010,Dadwal Motors Vancouver,British Columbia,Lower Mainland,1.20

In [85]:
# Create DimSalesperson

dim_salesperson = (
    salespeople[
        [
            "SalespersonID",
            "SalespersonName",
            "DealershipID",
            "SalesTeam",
            "PerformanceTier",
            "PerformanceWeight"
        ]
    ]
    .drop_duplicates("SalespersonID")
    .copy()
)

# Recalculate the transaction-level influence factor
dim_salesperson["SalesInfluenceWeight"] = (
    dim_salesperson["PerformanceWeight"] * 1.15
)

print("DimSalesperson created.")

print(f"Rows: {len(dim_salesperson):,}")

print(
    f"Unique SalespersonIDs: "
    f"{dim_salesperson['SalespersonID'].nunique():,}"
)

print(
    f"Duplicate SalespersonIDs: "
    f"{dim_salesperson['SalespersonID'].duplicated().sum():,}"
)

print(
    f"Missing SalespersonIDs: "
    f"{dim_salesperson['SalespersonID'].isna().sum():,}"
)

print("\nSalespeople by performance tier:")

display(
    dim_salesperson
    .groupby("PerformanceTier")
    .agg(
        Salespeople=("SalespersonID", "count"),
        AvgPerformanceWeight=("PerformanceWeight", "mean"),
        MinWeight=("PerformanceWeight", "min"),
        MaxWeight=("PerformanceWeight", "max")
    )
    .round(3)
)

print("\nSalespeople by dealership:")

display(
    dim_salesperson
    .groupby("DealershipID")
    .size()
    .rename("Salespeople")
    .to_frame()
)

print("\nSample:")

display(dim_salesperson.head(10))

DimSalesperson created.
Rows: 80
Unique SalespersonIDs: 80
Duplicate SalespersonIDs: 0
Missing SalespersonIDs: 0

Salespeople by performance tier:

                   Salespeople  AvgPerformanceWeight  MinWeight  MaxWeight
PerformanceTier
Average Performer           29                 0.961      0.905      1.049
Developing                  11                 0.772      0.704      0.855
Strong Performer            24                 1.139      1.055      1.189
Top Performer               16                 1.339      1.208      1.434

Salespeople by dealership:

              Salespeople
DealershipID
D001                    8
D002                    8
D003                    8
D004                    8
D005                    8
D006                    8
D007                    8
D008                    8
D009                    8
D010                    8

Sample:

,SalespersonID,SalespersonName,DealershipID,SalesTeam,PerformanceTier,PerformanceWeight,SalesInfluenceWeight
0,SP001,Michael King,D001,Retail,Average Performer,0.980636,1.127731
1,SP002,James Brown,D001,Retail,Top Performer,1.271037,1.461693
2,SP003,Alex Walker,D001,Retail,Developing,0.787279,0.905371
3,SP004,David Baker,D001,Retail,Average Performer,1.006429,1.157393
4,SP005,Daniel Brooks,D001,Retail,Average Performer,0.980149,1.127171
5,SP006,Ryan Clark,D001,Retail,Average Performer,0.930941,1.070582
6,SP007,Michael Taylor,D001,Commercial,Strong Performer,1.189347,1.367749
7,SP008,Sophia Walker,D001,Fleet,Top Performer,1.371836,1.577612
8,SP009,Ryan Brooks,D002,Retail,Strong Performer,1.163347,1.337849
9,SP010,Daniel Morgan,D002,Retail,Strong Performer,1.064192,1.223821

In [86]:
# Create DimDate

date_range = pd.date_range(
    start="2022-01-01",
    end="2025-12-31",
    freq="D"
)

dim_date = pd.DataFrame({
    "Date": date_range
})

dim_date["Year"] = (
    dim_date["Date"].dt.year
)

dim_date["MonthNumber"] = (
    dim_date["Date"].dt.month
)

dim_date["MonthName"] = (
    dim_date["Date"].dt.month_name()
)

dim_date["MonthShortName"] = (
    dim_date["Date"].dt.strftime("%b")
)

dim_date["QuarterNumber"] = (
    dim_date["Date"].dt.quarter
)

dim_date["Quarter"] = (
    "Q"
    + dim_date["QuarterNumber"].astype(str)
)

dim_date["YearMonth"] = (
    dim_date["Date"].dt.strftime("%Y-%m")
)

dim_date["YearQuarter"] = (
    dim_date["Year"].astype(str)
    + "-Q"
    + dim_date["QuarterNumber"].astype(str)
)

dim_date["MonthStart"] = (
    dim_date["Date"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

dim_date["DayOfMonth"] = (
    dim_date["Date"].dt.day
)

dim_date["DayOfWeekNumber"] = (
    dim_date["Date"].dt.dayofweek + 1
)

dim_date["DayOfWeekName"] = (
    dim_date["Date"].dt.day_name()
)

dim_date["IsWeekend"] = (
    dim_date["Date"].dt.dayofweek >= 5
)

print("DimDate created.")

print(f"Rows: {len(dim_date):,}")

print(
    f"Minimum date: "
    f"{dim_date['Date'].min().date()}"
)

print(
    f"Maximum date: "
    f"{dim_date['Date'].max().date()}"
)

print(
    f"Unique dates: "
    f"{dim_date['Date'].nunique():,}"
)

print(
    f"Duplicate dates: "
    f"{dim_date['Date'].duplicated().sum():,}"
)

print(
    f"Missing dates: "
    f"{dim_date['Date'].isna().sum():,}"
)

print("\nDays by year:")

display(
    dim_date
    .groupby("Year")
    .size()
    .rename("Days")
    .to_frame()
)

print("\nSample:")

display(dim_date.head(10))

DimDate created.
Rows: 1,461
Minimum date: 2022-01-01
Maximum date: 2025-12-31
Unique dates: 1,461
Duplicate dates: 0
Missing dates: 0

Days by year:

      Days
Year
2022   365
2023   365
2024   366
2025   365

Sample:

,Date,Year,MonthNumber,MonthName,MonthShortName,QuarterNumber,Quarter,YearMonth,YearQuarter,MonthStart,DayOfMonth,DayOfWeekNumber,DayOfWeekName,IsWeekend
0,2022-01-01,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,1,6,Saturday,True
1,2022-01-02,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,2,7,Sunday,True
2,2022-01-03,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,3,1,Monday,False
3,2022-01-04,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,4,2,Tuesday,False
4,2022-01-05,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,5,3,Wednesday,False
5,2022-01-06,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,6,4,Thursday,False
6,2022-01-07,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,7,5,Friday,False
7,2022-01-08,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,8,6,Saturday,True
8,2022-01-09,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,9,7,Sunday,True
9,2022-01-10,2022,1,January,Jan,1,Q1,2022-01,2022-Q1,2022-01-01,10,1,Monday,False

In [87]:
# Create FactSales
#
# Keep transaction-level business metrics and foreign keys.
# Descriptive attributes belong in the dimension tables.

fact_columns = [
    # Transaction identifiers
    "SalesID",
    "SalesDate",

    # Dimension keys
    "CustomerID",
    "DealershipID",
    "SalespersonID",
    "VehicleID",

    # Transaction attributes
    "SalesChannel",
    "PaymentMethod",
    "PaymentTermMonths",

    # Customer lifecycle
    "CustomerPurchaseNumber",
    "CustomerPurchaseType",
    "DaysSincePreviousPurchase",
    "PurchaseIntervalBand",
    "CustomerTenureMonths",
    "CustomerTenureBand",

    # Financial inputs
    "Quantity",
    "MSRP",
    "ActualCost",

    # Pricing / discount
    "BaseDiscountRate",
    "PromotionAdjustment",
    "FinalDiscountRate",
    "MarketAdjustmentRate",
    "SalePrice",

    # Financial outputs
    "Revenue",
    "GrossProfit",
    "GrossMarginRate",

    # Modeling drivers
    "GrowthFactor",
    "SeasonalityFactor",
    "MonthStart"
]

fact_sales = (
    transaction_base[fact_columns]
    .copy()
)

print("=" * 60)
print("FACT SALES CREATED")
print("=" * 60)

print(f"\nRows: {len(fact_sales):,}")

print(
    f"Unique SalesIDs: "
    f"{fact_sales['SalesID'].nunique():,}"
)

print(
    f"Duplicate SalesIDs: "
    f"{fact_sales['SalesID'].duplicated().sum():,}"
)

print(
    f"Missing values: "
    f"{fact_sales.isna().sum().sum():,}"
)

print("\nForeign-key coverage:")

print(
    f"Customers:   "
    f"{fact_sales['CustomerID'].nunique():,}"
)

print(
    f"Dealerships: "
    f"{fact_sales['DealershipID'].nunique():,}"
)

print(
    f"Salespeople: "
    f"{fact_sales['SalespersonID'].nunique():,}"
)

print(
    f"Vehicles:    "
    f"{fact_sales['VehicleID'].nunique():,}"
)

print("\nFinancial totals:")

print(
    f"Revenue:      "
    f"${fact_sales['Revenue'].sum():,.0f}"
)

print(
    f"Gross Profit: "
    f"${fact_sales['GrossProfit'].sum():,.0f}"
)

print(
    f"Average Margin: "
    f"{fact_sales['GrossMarginRate'].mean():.2%}"
)

print("\nSample:")

display(
    fact_sales.head(10)
)

============================================================
FACT SALES CREATED
============================================================

Rows: 531,482
Unique SalesIDs: 531,482
Duplicate SalesIDs: 0
Missing values: 123,258

Foreign-key coverage:
Customers:   123,258
Dealerships: 10
Salespeople: 80
Vehicles:    25

Financial totals:
Revenue:      $27,120,289,700
Gross Profit: $4,382,408,900
Average Margin: 16.25%

Sample:

,SalesID,SalesDate,CustomerID,DealershipID,SalespersonID,VehicleID,SalesChannel,PaymentMethod,PaymentTermMonths,CustomerPurchaseNumber,...,PromotionAdjustment,FinalDiscountRate,MarketAdjustmentRate,SalePrice,Revenue,GrossProfit,GrossMarginRate,GrowthFactor,SeasonalityFactor,MonthStart
0,S003093,2022-04-18,C000001,D001,SP004,V022,Showroom,Financing,48,1,...,0.000,0.008877,-0.007924,61000.0,61000.0,11300.0,0.185246,1.00,1.00,2022-04-01
1,S125509,2022-10-03,C000001,D003,SP017,V019,Showroom,Financing,72,2,...,0.005,0.022228,0.007519,52200.0,52200.0,10900.0,0.208812,1.00,1.02,2022-10-01
2,S245457,2023-03-26,C000001,D005,SP038,V011,Online,Financing,60,3,...,0.000,0.001668,0.009519,50400.0,50400.0,12500.0,0.248016,1.06,0.95,2023-03-01
3,S254673,2023-11-14,C000001,D005,SP033,V024,Showroom,Financing,60,4,...,0.010,0.028825,-0.009945,52900.0,52900.0,9600.0,0.181474,1.06,1.12,2023-11-01
4,S146955,2024-03-30,C000001,D003,SP020,V016,Online,Financing,60,5,...,0.000,0.009832,0.009420,27000.0,27000.0,5700.0,0.211111,1.11,0.95,2024-03-01
5,S414573,2025-04-21,C000001,D008,SP064,V004,Showroom,Financing,48,6,...,0.000,0.024002,0.009571,70900.0,70900.0,13000.0,0.183357,1.17,1.00,2025-04-01
6,S242574,2022-12-11,C000002,D005,SP038,V005,Showroom,Cash,0,1,...,0.015,0.070805,0.000752,43700.0,43700.0,5900.0,0.135011,1.00,1.18,2022-12-01
7,S097863,2025-01-18,C000002,D002,SP015,V019,Phone,Financing,48,2,...,0.000,0.039487,0.007653,51300.0,51300.0,9400.0,0.183236,1.17,0.85,2025-01-01
8,S320068,2025-07-02,C000002,D006,SP044,V013,Phone,Financing,72,3,...,0.005,0.072923,-0.009130,68900.0,68900.0,9000.0,0.130624,1.17,1.08,2025-07-01
9,S474474,2022-02-05,C000003,D010,SP079,V010,Showroom,Lease,48,1,...,0.000,0.040041,0.001648,43300.0,43300.0,6700.0,0.154734,1.00,0.90,2022-02-01

In [88]:
# Validate FactSales foreign keys against dimension tables

print("=" * 70)
print("FOREIGN KEY REFERENTIAL INTEGRITY")
print("=" * 70)


def validate_foreign_key(
    fact_df,
    fact_key,
    dimension_df,
    dimension_key,
    dimension_name
):

    fact_values = set(
        fact_df[fact_key].dropna().unique()
    )

    dimension_values = set(
        dimension_df[dimension_key].dropna().unique()
    )

    orphan_values = fact_values - dimension_values

    orphan_rows = (
        fact_df[fact_df[fact_key].isin(orphan_values)]
        .shape[0]
    )

    print(
        f"\n{fact_key} → {dimension_name}"
    )

    print(
        f"Dimension keys: {len(dimension_values):,}"
    )

    print(
        f"Orphan key values: {len(orphan_values):,}"
    )

    print(
        f"Orphan fact rows: {orphan_rows:,}"
    )

    return orphan_rows


orphan_customer = validate_foreign_key(
    fact_sales,
    "CustomerID",
    dim_customer,
    "CustomerID",
    "DimCustomer"
)

orphan_vehicle = validate_foreign_key(
    fact_sales,
    "VehicleID",
    dim_vehicle,
    "VehicleID",
    "DimVehicle"
)

orphan_dealership = validate_foreign_key(
    fact_sales,
    "DealershipID",
    dim_dealership,
    "DealershipID",
    "DimDealership"
)

orphan_salesperson = validate_foreign_key(
    fact_sales,
    "SalespersonID",
    dim_salesperson,
    "SalespersonID",
    "DimSalesperson"
)

orphan_dates = validate_foreign_key(
    fact_sales,
    "SalesDate",
    dim_date,
    "Date",
    "DimDate"
)

print("\n" + "=" * 70)

total_orphans = (
    orphan_customer
    + orphan_vehicle
    + orphan_dealership
    + orphan_salesperson
    + orphan_dates
)

print(
    f"Total orphan fact rows: {total_orphans:,}"
)

print("=" * 70)

======================================================================
FOREIGN KEY REFERENTIAL INTEGRITY
======================================================================

CustomerID → DimCustomer
Dimension keys: 125,000
Orphan key values: 0
Orphan fact rows: 0

VehicleID → DimVehicle
Dimension keys: 25
Orphan key values: 0
Orphan fact rows: 0

DealershipID → DimDealership
Dimension keys: 10
Orphan key values: 0
Orphan fact rows: 0

SalespersonID → DimSalesperson
Dimension keys: 80
Orphan key values: 0
Orphan fact rows: 0

SalesDate → DimDate
Dimension keys: 1,461
Orphan key values: 0
Orphan fact rows: 0

======================================================================
Total orphan fact rows: 0
======================================================================

In [89]:
# ============================================================
# FINAL DATASET FREEZE VALIDATION
# ============================================================

print("=" * 70)
print("FINAL DATASET FREEZE VALIDATION")
print("=" * 70)

expected_counts = {
    "FactSales": 531_482,
    "DimCustomer": 125_000,
    "DimVehicle": 25,
    "DimDealership": 10,
    "DimSalesperson": 80,
    "DimDate": 1_461
}

actual_counts = {
    "FactSales": len(fact_sales),
    "DimCustomer": len(dim_customer),
    "DimVehicle": len(dim_vehicle),
    "DimDealership": len(dim_dealership),
    "DimSalesperson": len(dim_salesperson),
    "DimDate": len(dim_date)
}

print("\nRow-count validation:")

all_counts_correct = True

for table_name, expected in expected_counts.items():

    actual = actual_counts[table_name]

    status = "PASS" if actual == expected else "FAIL"

    print(
        f"{table_name:<18} "
        f"Expected: {expected:>10,} | "
        f"Actual: {actual:>10,} | "
        f"{status}"
    )

    if actual != expected:
        all_counts_correct = False


print("\nKey validation:")

checks = {
    "FactSales unique SalesID":
        fact_sales["SalesID"].nunique() == len(fact_sales),

    "DimCustomer unique CustomerID":
        dim_customer["CustomerID"].nunique() == len(dim_customer),

    "DimVehicle unique VehicleID":
        dim_vehicle["VehicleID"].nunique() == len(dim_vehicle),

    "DimDealership unique DealershipID":
        dim_dealership["DealershipID"].nunique() == len(dim_dealership),

    "DimSalesperson unique SalespersonID":
        dim_salesperson["SalespersonID"].nunique() == len(dim_salesperson),

    "DimDate unique Date":
        dim_date["Date"].nunique() == len(dim_date)
}

all_keys_correct = True

for check_name, result in checks.items():

    print(
        f"{check_name:<40} "
        f"{'PASS' if result else 'FAIL'}"
    )

    if not result:
        all_keys_correct = False


print("\nFinancial validation:")

revenue = fact_sales["Revenue"].sum()
gross_profit = fact_sales["GrossProfit"].sum()
avg_margin = fact_sales["GrossMarginRate"].mean()

print(f"Revenue:      ${revenue:,.0f}")
print(f"Gross Profit: ${gross_profit:,.0f}")
print(f"Average Margin: {avg_margin:.2%}")


print("\n" + "=" * 70)

if all_counts_correct and all_keys_correct:
    print("DATASET STATUS: FROZEN")
    print("No structural validation failures detected.")
else:
    print("DATASET STATUS: NOT FROZEN")
    print("Resolve validation failures before exporting.")

print("=" * 70)

======================================================================
FINAL DATASET FREEZE VALIDATION
======================================================================

Row-count validation:
FactSales          Expected:    531,482 | Actual:    531,482 | PASS
DimCustomer        Expected:    125,000 | Actual:    125,000 | PASS
DimVehicle         Expected:         25 | Actual:         25 | PASS
DimDealership      Expected:         10 | Actual:         10 | PASS
DimSalesperson     Expected:         80 | Actual:         80 | PASS
DimDate            Expected:      1,461 | Actual:      1,461 | PASS

Key validation:
FactSales unique SalesID                 PASS
DimCustomer unique CustomerID            PASS
DimVehicle unique VehicleID              PASS
DimDealership unique DealershipID        PASS
DimSalesperson unique SalespersonID      PASS
DimDate unique Date                      PASS

Financial validation:
Revenue:      $27,120,289,700
Gross Profit: $4,382,408,900
Average Margin: 16.25%

======================================================================
DATASET STATUS: FROZEN
No structural validation failures detected.
======================================================================

In [90]:
# ============================================================
# CREATE FROZEN SNAPSHOT
# ============================================================

FactSales_Frozen = fact_sales.copy(deep=True)
DimCustomer_Frozen = dim_customer.copy(deep=True)
DimVehicle_Frozen = dim_vehicle.copy(deep=True)
DimDealership_Frozen = dim_dealership.copy(deep=True)
DimSalesperson_Frozen = dim_salesperson.copy(deep=True)
DimDate_Frozen = dim_date.copy(deep=True)

print("Frozen snapshot created.")

Frozen snapshot created.

In [91]:
# ============================================================
# EXPORT FROZEN TABLES
# ============================================================

from pathlib import Path

export_path = Path("data/processed")
export_path.mkdir(parents=True, exist_ok=True)

frozen_tables = {
    "FactSales.csv": FactSales_Frozen,
    "DimCustomer.csv": DimCustomer_Frozen,
    "DimVehicle.csv": DimVehicle_Frozen,
    "DimDealership.csv": DimDealership_Frozen,
    "DimSalesperson.csv": DimSalesperson_Frozen,
    "DimDate.csv": DimDate_Frozen
}

for filename, df in frozen_tables.items():

    output_file = export_path / filename

    df.to_csv(
        output_file,
        index=False
    )

    print(
        f"✓ {filename:<22} "
        f"{len(df):,} rows"
    )

print("\nExport complete.")

✓ FactSales.csv          531,482 rows
✓ DimCustomer.csv        125,000 rows
✓ DimVehicle.csv         25 rows
✓ DimDealership.csv      10 rows
✓ DimSalesperson.csv     80 rows
✓ DimDate.csv            1,461 rows

Export complete.

In [92]:
# ============================================================
# VERIFY FROZEN EXPORTS
# ============================================================

print("=" * 70)
print("FROZEN EXPORT VALIDATION")
print("=" * 70)

expected_rows = {
    "FactSales.csv": 531_482,
    "DimCustomer.csv": 125_000,
    "DimVehicle.csv": 25,
    "DimDealership.csv": 10,
    "DimSalesperson.csv": 80,
    "DimDate.csv": 1_461
}

all_pass = True

for filename, expected in expected_rows.items():

    file_path = export_path / filename

    check = pd.read_csv(file_path)

    passed = len(check) == expected

    print(
        f"{filename:<24} "
        f"{len(check):>10,} / "
        f"{expected:>10,} "
        f"{'PASS' if passed else 'FAIL'}"
    )

    if not passed:
        all_pass = False

print("=" * 70)

print(
    "EXPORT STATUS:",
    "READY FOR POWER BI" if all_pass else "FAILED"
)

======================================================================
FROZEN EXPORT VALIDATION
======================================================================
FactSales.csv               531,482 /    531,482 PASS
DimCustomer.csv             125,000 /    125,000 PASS
DimVehicle.csv                   25 /         25 PASS
DimDealership.csv                10 /         10 PASS
DimSalesperson.csv               80 /         80 PASS
DimDate.csv                   1,461 /      1,461 PASS
======================================================================
EXPORT STATUS: READY FOR POWER BI

In [93]:
from google.colab import files
import shutil

shutil.make_archive(
    "/content/Dadwal_Motors_PowerBI_Data",
    "zip",
    "/content/data/processed"
)

files.download("/content/Dadwal_Motors_PowerBI_Data.zip")